-- GENERATED by debug/generate-residency-ddl.ts, do not edit by hand.
-- Source: central Supabase live schema, 2026-08-27T06:42:41.354Z
-- Tables: 15 (RESIDENCY_MOVED_TABLES)
--
-- Single-tenant datastore for the per-VPS data API. RLS is intentionally
-- absent (one tenant per box; the data-api bearer token is the boundary).
-- FKs to central control-plane tables (businesses, …) are dropped.

create extension if not exists pgcrypto;

create table if not exists residency_schema_meta (
  key text primary key,
  value text not null
);

-- ── contacts ────────────────────────────────────────────────────
create table if not exists contacts (
  id uuid not null default gen_random_uuid(),
  business_id uuid not null,
  customer_e164 text not null,
  display_name text,
  summary_md text,
  pinned_md text,
  interaction_count integer not null default 0,
  total_interaction_count integer not null default 0,
  last_interaction_at timestamp with time zone,
  last_summarized_at timestamp with time zone,
  last_channel text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  alias_e164s text[] not null default '{}'::text[],
  email text,
  type text not null default 'customer'::text,
  name_source text not null default 'auto'::text,
  sms_reply_mode text not null default 'auto'::text,
  tags text[] not null default '{}'::text[],
  owner_employee_id uuid,
  birthday date,
  marketing_unsubscribed_at timestamp with time zone,
  preferred_language text,
  language_source text,
  lead_source text,
  constraint customer_memories_business_id_customer_e164_key UNIQUE (business_id, customer_e164),
  constraint customer_memories_pkey PRIMARY KEY (id),
  constraint contacts_email_key_matches_email CHECK (((customer_e164 !~~ 'email:%'::text) OR (lower(COALESCE(email, ''::text)) = SUBSTRING(lower(customer_e164) FROM 7)))),
  constraint contacts_language_source_check CHECK (((language_source IS NULL) OR (language_source = ANY (ARRAY['detected'::text, 'owner_set'::text])))),
  constraint contacts_lead_source_len_chk CHECK (((lead_source IS NULL) OR (char_length(lead_source) <= 120))),
  constraint contacts_name_source_chk CHECK ((name_source = ANY (ARRAY['auto'::text, 'manual'::text]))),
  constraint contacts_sms_reply_mode_chk CHECK ((sms_reply_mode = ANY (ARRAY['auto'::text, 'suppress'::text, 'forward_owner'::text]))),
  constraint contacts_tags_cap_chk CHECK ((cardinality(tags) <= 25)),
  constraint contacts_type_chk CHECK ((type = ANY (ARRAY['owner'::text, 'employee'::text, 'customer'::text, 'tester'::text, 'company'::text, 'other'::text]))),
  constraint customer_memories_last_channel_check CHECK ((last_channel = ANY (ARRAY['sms'::text, 'voice'::text, 'dashboard'::text, 'email'::text, 'webchat'::text, 'messenger'::text, 'whatsapp'::text, 'booking_page'::text])))
);

alter table contacts add column if not exists id uuid not null default gen_random_uuid();
alter table contacts add column if not exists business_id uuid;
alter table contacts add column if not exists customer_e164 text;
alter table contacts add column if not exists display_name text;
alter table contacts add column if not exists summary_md text;
alter table contacts add column if not exists pinned_md text;
alter table contacts add column if not exists interaction_count integer not null default 0;
alter table contacts add column if not exists total_interaction_count integer not null default 0;
alter table contacts add column if not exists last_interaction_at timestamp with time zone;
alter table contacts add column if not exists last_summarized_at timestamp with time zone;
alter table contacts add column if not exists last_channel text;
alter table contacts add column if not exists created_at timestamp with time zone not null default now();
alter table contacts add column if not exists updated_at timestamp with time zone not null default now();
alter table contacts add column if not exists alias_e164s text[] not null default '{}'::text[];
alter table contacts add column if not exists email text;
alter table contacts add column if not exists type text not null default 'customer'::text;
alter table contacts add column if not exists name_source text not null default 'auto'::text;
alter table contacts add column if not exists sms_reply_mode text not null default 'auto'::text;
alter table contacts add column if not exists tags text[] not null default '{}'::text[];
alter table contacts add column if not exists owner_employee_id uuid;
alter table contacts add column if not exists birthday date;
alter table contacts add column if not exists marketing_unsubscribed_at timestamp with time zone;
alter table contacts add column if not exists preferred_language text;
alter table contacts add column if not exists language_source text;
alter table contacts add column if not exists lead_source text;

do $$ declare c record; begin
  for c in select conname from pg_constraint
            where conrelid = 'contacts'::regclass and contype = 'c' loop
    execute format('alter table contacts drop constraint %I', c.conname);
  end loop;
end $$;
alter table contacts add constraint contacts_email_key_matches_email CHECK (((customer_e164 !~~ 'email:%'::text) OR (lower(COALESCE(email, ''::text)) = SUBSTRING(lower(customer_e164) FROM 7))));
alter table contacts add constraint contacts_language_source_check CHECK (((language_source IS NULL) OR (language_source = ANY (ARRAY['detected'::text, 'owner_set'::text]))));
alter table contacts add constraint contacts_lead_source_len_chk CHECK (((lead_source IS NULL) OR (char_length(lead_source) <= 120)));
alter table contacts add constraint contacts_name_source_chk CHECK ((name_source = ANY (ARRAY['auto'::text, 'manual'::text])));
alter table contacts add constraint contacts_sms_reply_mode_chk CHECK ((sms_reply_mode = ANY (ARRAY['auto'::text, 'suppress'::text, 'forward_owner'::text])));
alter table contacts add constraint contacts_tags_cap_chk CHECK ((cardinality(tags) <= 25));
alter table contacts add constraint contacts_type_chk CHECK ((type = ANY (ARRAY['owner'::text, 'employee'::text, 'customer'::text, 'tester'::text, 'company'::text, 'other'::text])));
alter table contacts add constraint customer_memories_last_channel_check CHECK ((last_channel = ANY (ARRAY['sms'::text, 'voice'::text, 'dashboard'::text, 'email'::text, 'webchat'::text, 'messenger'::text, 'whatsapp'::text, 'booking_page'::text])));

create index if not exists contacts_birthday_idx ON public.contacts USING btree (business_id) WHERE (birthday IS NOT NULL);
create index if not exists contacts_owner_employee_idx ON public.contacts USING btree (business_id, owner_employee_id) WHERE (owner_employee_id IS NOT NULL);
create index if not exists contacts_tags_gin_idx ON public.contacts USING gin (tags);
create index if not exists customer_memories_business_email_idx ON public.contacts USING btree (business_id, lower(email)) WHERE (email IS NOT NULL);
create index if not exists idx_contacts_business_lead_source ON public.contacts USING btree (business_id, lead_source) WHERE (lead_source IS NOT NULL);
create index if not exists idx_contacts_owner_employee_id ON public.contacts USING btree (owner_employee_id);
create index if not exists idx_customer_memories_alias_gin ON public.contacts USING gin (alias_e164s);
create index if not exists idx_customer_memories_business_recent ON public.contacts USING btree (business_id, last_interaction_at DESC);
create index if not exists idx_customer_memories_summary_due ON public.contacts USING btree (business_id, last_summarized_at) WHERE (interaction_count >= 1);

-- ── dashboard_chat_threads ──────────────────────────────────────
create table if not exists dashboard_chat_threads (
  id uuid not null default gen_random_uuid(),
  business_id uuid not null,
  rowboat_conversation_id text,
  rowboat_state jsonb,
  title text,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  summary_md text,
  summary_message_count integer not null default 0,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  constraint dashboard_chat_threads_pkey PRIMARY KEY (id)
);

alter table dashboard_chat_threads add column if not exists id uuid not null default gen_random_uuid();
alter table dashboard_chat_threads add column if not exists business_id uuid;
alter table dashboard_chat_threads add column if not exists rowboat_conversation_id text;
alter table dashboard_chat_threads add column if not exists rowboat_state jsonb;
alter table dashboard_chat_threads add column if not exists title text;
alter table dashboard_chat_threads add column if not exists is_active boolean not null default true;
alter table dashboard_chat_threads add column if not exists created_at timestamp with time zone not null default now();
alter table dashboard_chat_threads add column if not exists updated_at timestamp with time zone not null default now();
alter table dashboard_chat_threads add column if not exists summary_md text;
alter table dashboard_chat_threads add column if not exists summary_message_count integer not null default 0;
alter table dashboard_chat_threads add column if not exists deleted_at timestamp with time zone;
alter table dashboard_chat_threads add column if not exists deleted_by uuid;

do $$ declare c record; begin
  for c in select conname from pg_constraint
            where conrelid = 'dashboard_chat_threads'::regclass and contype = 'c' loop
    execute format('alter table dashboard_chat_threads drop constraint %I', c.conname);
  end loop;
end $$;

create index if not exists dashboard_chat_threads_business_idx ON public.dashboard_chat_threads USING btree (business_id, created_at DESC);
create index if not exists dashboard_chat_threads_deleted_idx ON public.dashboard_chat_threads USING btree (business_id, deleted_at DESC) WHERE (deleted_at IS NOT NULL);
create unique index if not exists dashboard_chat_threads_one_active ON public.dashboard_chat_threads USING btree (business_id) WHERE is_active;

-- ── dashboard_chat_messages ─────────────────────────────────────
create table if not exists dashboard_chat_messages (
  id bigint not null generated by default as identity,
  thread_id uuid not null,
  role text not null,
  content text not null,
  created_at timestamp with time zone not null default now(),
  constraint dashboard_chat_messages_pkey PRIMARY KEY (id),
  constraint dashboard_chat_messages_role_check CHECK ((role = ANY (ARRAY['user'::text, 'assistant'::text, 'system'::text])))
);

alter table dashboard_chat_messages add column if not exists id bigint not null generated by default as identity;
alter table dashboard_chat_messages add column if not exists thread_id uuid;
alter table dashboard_chat_messages add column if not exists role text;
alter table dashboard_chat_messages add column if not exists content text;
alter table dashboard_chat_messages add column if not exists created_at timestamp with time zone not null default now();

do $$ declare c record; begin
  for c in select conname from pg_constraint
            where conrelid = 'dashboard_chat_messages'::regclass and contype = 'c' loop
    execute format('alter table dashboard_chat_messages drop constraint %I', c.conname);
  end loop;
end $$;
alter table dashboard_chat_messages add constraint dashboard_chat_messages_role_check CHECK ((role = ANY (ARRAY['user'::text, 'assistant'::text, 'system'::text])));

create index if not exists dashboard_chat_messages_thread_idx ON public.dashboard_chat_messages USING btree (thread_id, created_at);

-- ── dashboard_chat_activity ─────────────────────────────────────
create table if not exists dashboard_chat_activity (
  business_id uuid not null,
  last_user_chat_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint dashboard_chat_activity_pkey PRIMARY KEY (business_id)
);

alter table dashboard_chat_activity add column if not exists business_id uuid;
alter table dashboard_chat_activity add column if not exists last_user_chat_at timestamp with time zone not null default now();
alter table dashboard_chat_activity add column if not exists updated_at timestamp with time zone not null default now();

do $$ declare c record; begin
  for c in select conname from pg_constraint
            where conrelid = 'dashboard_chat_activity'::regclass and contype = 'c' loop
    execute format('alter table dashboard_chat_activity drop constraint %I', c.conname);
  end loop;
end $$;


-- ── email_log ───────────────────────────────────────────────────
create table if not exists email_log (
  id uuid not null default gen_random_uuid(),
  business_id uuid not null,
  direction text not null,
  to_email text,
  from_email text,
  subject text,
  body_preview text,
  source text not null,
  run_id uuid,
  flow_id uuid,
  provider_message_id text,
  created_at timestamp with time zone not null default now(),
  cc_email text,
  bcc_email text,
  body_full text,
  attachments jsonb not null default '[]'::jsonb,
  body_html text,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  is_read boolean not null default true,
  archived_at timestamp with time zone,
  folder text,
  labels text[] not null default '{}'::text[],
  thread_id text,
  message_ref text,
  importance smallint,
  delivery_status text,
  delivery_error_code text,
  delivery_error_message text,
  delivery_updated_at timestamp with time zone,
  constraint email_log_pkey PRIMARY KEY (id),
  constraint email_log_delivery_status_check CHECK ((delivery_status = ANY (ARRAY['sent'::text, 'delayed'::text, 'delivered'::text, 'complained'::text, 'bounced'::text, 'failed'::text]))),
  constraint email_log_direction_check CHECK ((direction = ANY (ARRAY['outbound'::text, 'inbound'::text]))),
  constraint email_log_importance_check CHECK (((importance IS NULL) OR ((importance >= 1) AND (importance <= 10)))),
  constraint email_log_source_check CHECK ((source = ANY (ARRAY['ai_flow'::text, 'owner_mailbox'::text, 'email_trigger'::text, 'dashboard_chat'::text, 'sms_assistant'::text, 'voice_assistant'::text, 'slack_assistant'::text, 'telegram_assistant'::text, 'teams_assistant'::text, 'tenant_mailbox_inbound'::text, 'tenant_mailbox_outbound'::text, 'owner_manual'::text, 'email_coworker'::text, 'booking_reminder'::text, 'notification'::text])))
);

alter table email_log add column if not exists id uuid not null default gen_random_uuid();
alter table email_log add column if not exists business_id uuid;
alter table email_log add column if not exists direction text;
alter table email_log add column if not exists to_email text;
alter table email_log add column if not exists from_email text;
alter table email_log add column if not exists subject text;
alter table email_log add column if not exists body_preview text;
alter table email_log add column if not exists source text;
alter table email_log add column if not exists run_id uuid;
alter table email_log add column if not exists flow_id uuid;
alter table email_log add column if not exists provider_message_id text;
alter table email_log add column if not exists created_at timestamp with time zone not null default now();
alter table email_log add column if not exists cc_email text;
alter table email_log add column if not exists bcc_email text;
alter table email_log add column if not exists body_full text;
alter table email_log add column if not exists attachments jsonb not null default '[]'::jsonb;
alter table email_log add column if not exists body_html text;
alter table email_log add column if not exists deleted_at timestamp with time zone;
alter table email_log add column if not exists deleted_by uuid;
alter table email_log add column if not exists is_read boolean not null default true;
alter table email_log add column if not exists archived_at timestamp with time zone;
alter table email_log add column if not exists folder text;
alter table email_log add column if not exists labels text[] not null default '{}'::text[];
alter table email_log add column if not exists thread_id text;
alter table email_log add column if not exists message_ref text;
alter table email_log add column if not exists importance smallint;
alter table email_log add column if not exists delivery_status text;
alter table email_log add column if not exists delivery_error_code text;
alter table email_log add column if not exists delivery_error_message text;
alter table email_log add column if not exists delivery_updated_at timestamp with time zone;

do $$ declare c record; begin
  for c in select conname from pg_constraint
            where conrelid = 'email_log'::regclass and contype = 'c' loop
    execute format('alter table email_log drop constraint %I', c.conname);
  end loop;
end $$;
alter table email_log add constraint email_log_delivery_status_check CHECK ((delivery_status = ANY (ARRAY['sent'::text, 'delayed'::text, 'delivered'::text, 'complained'::text, 'bounced'::text, 'failed'::text])));
alter table email_log add constraint email_log_direction_check CHECK ((direction = ANY (ARRAY['outbound'::text, 'inbound'::text])));
alter table email_log add constraint email_log_importance_check CHECK (((importance IS NULL) OR ((importance >= 1) AND (importance <= 10))));
alter table email_log add constraint email_log_source_check CHECK ((source = ANY (ARRAY['ai_flow'::text, 'owner_mailbox'::text, 'email_trigger'::text, 'dashboard_chat'::text, 'sms_assistant'::text, 'voice_assistant'::text, 'slack_assistant'::text, 'telegram_assistant'::text, 'teams_assistant'::text, 'tenant_mailbox_inbound'::text, 'tenant_mailbox_outbound'::text, 'owner_manual'::text, 'email_coworker'::text, 'booking_reminder'::text, 'notification'::text])));

create index if not exists email_log_business_created_idx ON public.email_log USING btree (business_id, created_at DESC);
create index if not exists email_log_business_importance_idx ON public.email_log USING btree (business_id, importance DESC) WHERE (importance IS NOT NULL);
create index if not exists email_log_business_thread_idx ON public.email_log USING btree (business_id, thread_id) WHERE (thread_id IS NOT NULL);
create index if not exists email_log_deleted_idx ON public.email_log USING btree (business_id, deleted_at DESC) WHERE (deleted_at IS NOT NULL);
create index if not exists email_log_delivery_failed_idx ON public.email_log USING btree (business_id, delivery_updated_at DESC) WHERE (delivery_status = ANY (ARRAY['bounced'::text, 'complained'::text, 'failed'::text]));
create index if not exists email_log_organize_inbox_idx ON public.email_log USING btree (business_id, archived_at, created_at DESC) WHERE (deleted_at IS NULL);
create index if not exists email_log_provider_message_idx ON public.email_log USING btree (provider_message_id) WHERE (provider_message_id IS NOT NULL);

-- ── voice_call_transcripts ──────────────────────────────────────
create table if not exists voice_call_transcripts (
  id uuid not null default gen_random_uuid(),
  business_id uuid not null,
  call_control_id text not null,
  reservation_id uuid,
  caller_e164 text,
  model text not null,
  status text not null,
  started_at timestamp with time zone not null default now(),
  ended_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  direction text not null default 'inbound'::text,
  summary text,
  sentiment text,
  summarized_at timestamp with time zone,
  summary_error text,
  summary_attempts integer not null default 0,
  call_kind text not null default 'ai'::text,
  forwarded_to_e164 text,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  answering_machine_result text,
  voicemail_left boolean not null default false,
  voicemail_verbatim_score double precision,
  interpreted_from_turn_index integer,
  constraint voice_call_transcripts_call_control_id_key UNIQUE (call_control_id),
  constraint voice_call_transcripts_pkey PRIMARY KEY (id),
  constraint voice_call_transcripts_call_kind_check CHECK ((call_kind = ANY (ARRAY['ai'::text, 'forwarded'::text]))),
  constraint voice_call_transcripts_direction_check CHECK ((direction = ANY (ARRAY['inbound'::text, 'outbound'::text]))),
  constraint voice_call_transcripts_sentiment_check CHECK ((sentiment = ANY (ARRAY['positive'::text, 'neutral'::text, 'negative'::text, 'mixed'::text]))),
  constraint voice_call_transcripts_status_check CHECK ((status = ANY (ARRAY['in_progress'::text, 'completed'::text, 'errored'::text, 'missed'::text])))
);

alter table voice_call_transcripts add column if not exists id uuid not null default gen_random_uuid();
alter table voice_call_transcripts add column if not exists business_id uuid;
alter table voice_call_transcripts add column if not exists call_control_id text;
alter table voice_call_transcripts add column if not exists reservation_id uuid;
alter table voice_call_transcripts add column if not exists caller_e164 text;
alter table voice_call_transcripts add column if not exists model text;
alter table voice_call_transcripts add column if not exists status text;
alter table voice_call_transcripts add column if not exists started_at timestamp with time zone not null default now();
alter table voice_call_transcripts add column if not exists ended_at timestamp with time zone;
alter table voice_call_transcripts add column if not exists created_at timestamp with time zone not null default now();
alter table voice_call_transcripts add column if not exists updated_at timestamp with time zone not null default now();
alter table voice_call_transcripts add column if not exists direction text not null default 'inbound'::text;
alter table voice_call_transcripts add column if not exists summary text;
alter table voice_call_transcripts add column if not exists sentiment text;
alter table voice_call_transcripts add column if not exists summarized_at timestamp with time zone;
alter table voice_call_transcripts add column if not exists summary_error text;
alter table voice_call_transcripts add column if not exists summary_attempts integer not null default 0;
alter table voice_call_transcripts add column if not exists call_kind text not null default 'ai'::text;
alter table voice_call_transcripts add column if not exists forwarded_to_e164 text;
alter table voice_call_transcripts add column if not exists deleted_at timestamp with time zone;
alter table voice_call_transcripts add column if not exists deleted_by uuid;
alter table voice_call_transcripts add column if not exists answering_machine_result text;
alter table voice_call_transcripts add column if not exists voicemail_left boolean not null default false;
alter table voice_call_transcripts add column if not exists voicemail_verbatim_score double precision;
alter table voice_call_transcripts add column if not exists interpreted_from_turn_index integer;

do $$ declare c record; begin
  for c in select conname from pg_constraint
            where conrelid = 'voice_call_transcripts'::regclass and contype = 'c' loop
    execute format('alter table voice_call_transcripts drop constraint %I', c.conname);
  end loop;
end $$;
alter table voice_call_transcripts add constraint voice_call_transcripts_call_kind_check CHECK ((call_kind = ANY (ARRAY['ai'::text, 'forwarded'::text])));
alter table voice_call_transcripts add constraint voice_call_transcripts_direction_check CHECK ((direction = ANY (ARRAY['inbound'::text, 'outbound'::text])));
alter table voice_call_transcripts add constraint voice_call_transcripts_sentiment_check CHECK ((sentiment = ANY (ARRAY['positive'::text, 'neutral'::text, 'negative'::text, 'mixed'::text])));
alter table voice_call_transcripts add constraint voice_call_transcripts_status_check CHECK ((status = ANY (ARRAY['in_progress'::text, 'completed'::text, 'errored'::text, 'missed'::text])));

create index if not exists idx_voice_call_transcripts_reservation_id ON public.voice_call_transcripts USING btree (reservation_id);
create index if not exists voice_call_transcripts_business_idx ON public.voice_call_transcripts USING btree (business_id, created_at DESC);
create index if not exists voice_call_transcripts_deleted_idx ON public.voice_call_transcripts USING btree (business_id, deleted_at DESC) WHERE (deleted_at IS NOT NULL);
create index if not exists voice_call_transcripts_summary_pending_idx ON public.voice_call_transcripts USING btree (ended_at DESC) WHERE ((status = 'completed'::text) AND (summarized_at IS NULL));

-- ── voice_call_transcript_turns ─────────────────────────────────
create table if not exists voice_call_transcript_turns (
  id bigint not null generated by default as identity,
  transcript_id uuid not null,
  role text not null,
  content text not null,
  turn_index integer not null,
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  constraint voice_call_transcript_turns_transcript_id_turn_index_key UNIQUE (transcript_id, turn_index),
  constraint voice_call_transcript_turns_pkey PRIMARY KEY (id),
  constraint voice_call_transcript_turns_role_check CHECK ((role = ANY (ARRAY['caller'::text, 'assistant'::text])))
);

alter table voice_call_transcript_turns add column if not exists id bigint not null generated by default as identity;
alter table voice_call_transcript_turns add column if not exists transcript_id uuid;
alter table voice_call_transcript_turns add column if not exists role text;
alter table voice_call_transcript_turns add column if not exists content text;
alter table voice_call_transcript_turns add column if not exists turn_index integer;
alter table voice_call_transcript_turns add column if not exists started_at timestamp with time zone;
alter table voice_call_transcript_turns add column if not exists ended_at timestamp with time zone;
alter table voice_call_transcript_turns add column if not exists created_at timestamp with time zone not null default now();

do $$ declare c record; begin
  for c in select conname from pg_constraint
            where conrelid = 'voice_call_transcript_turns'::regclass and contype = 'c' loop
    execute format('alter table voice_call_transcript_turns drop constraint %I', c.conname);
  end loop;
end $$;
alter table voice_call_transcript_turns add constraint voice_call_transcript_turns_role_check CHECK ((role = ANY (ARRAY['caller'::text, 'assistant'::text])));

create index if not exists voice_call_transcript_turns_thread_idx ON public.voice_call_transcript_turns USING btree (transcript_id, created_at);

-- ── voice_outbound_dial_log ─────────────────────────────────────
create table if not exists voice_outbound_dial_log (
  id uuid not null default gen_random_uuid(),
  flow_id uuid not null,
  business_id uuid not null,
  dedupe_key text not null,
  call_control_id text,
  status text not null default 'placed'::text,
  reason text,
  created_at timestamp with time zone not null default now(),
  to_e164 text,
  constraint voice_outbound_dial_log_flow_id_dedupe_key_key UNIQUE (flow_id, dedupe_key),
  constraint voice_outbound_dial_log_pkey PRIMARY KEY (id),
  constraint voice_outbound_dial_log_status_check CHECK ((status = ANY (ARRAY['placed'::text, 'blocked'::text, 'failed'::text])))
);

alter table voice_outbound_dial_log add column if not exists id uuid not null default gen_random_uuid();
alter table voice_outbound_dial_log add column if not exists flow_id uuid;
alter table voice_outbound_dial_log add column if not exists business_id uuid;
alter table voice_outbound_dial_log add column if not exists dedupe_key text;
alter table voice_outbound_dial_log add column if not exists call_control_id text;
alter table voice_outbound_dial_log add column if not exists status text not null default 'placed'::text;
alter table voice_outbound_dial_log add column if not exists reason text;
alter table voice_outbound_dial_log add column if not exists created_at timestamp with time zone not null default now();
alter table voice_outbound_dial_log add column if not exists to_e164 text;

do $$ declare c record; begin
  for c in select conname from pg_constraint
            where conrelid = 'voice_outbound_dial_log'::regclass and contype = 'c' loop
    execute format('alter table voice_outbound_dial_log drop constraint %I', c.conname);
  end loop;
end $$;
alter table voice_outbound_dial_log add constraint voice_outbound_dial_log_status_check CHECK ((status = ANY (ARRAY['placed'::text, 'blocked'::text, 'failed'::text])));

create index if not exists idx_voice_outbound_dial_log_business ON public.voice_outbound_dial_log USING btree (business_id, created_at DESC);
create index if not exists idx_voice_outbound_dial_log_to_e164 ON public.voice_outbound_dial_log USING btree (business_id, to_e164, created_at DESC);

-- ── sms_outbound_log ────────────────────────────────────────────
create table if not exists sms_outbound_log (
  id uuid not null default gen_random_uuid(),
  business_id uuid not null,
  to_e164 text not null,
  from_e164 text,
  body text not null,
  source text not null,
  run_id uuid,
  flow_id uuid,
  telnyx_message_id text,
  created_at timestamp with time zone not null default now(),
  channel text not null default 'sms'::text,
  scheduled_sms_id uuid,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  destination_country text,
  constraint sms_outbound_log_pkey PRIMARY KEY (id),
  constraint sms_outbound_log_channel_check CHECK ((channel = ANY (ARRAY['sms'::text, 'rcs'::text]))),
  constraint sms_outbound_log_source_check CHECK ((source = ANY (ARRAY['ai_flow'::text, 'agent_offer'::text, 'owner_notify'::text, 'owner_manual'::text, 'owner_scheduled'::text, 'api'::text, 'voice_follow_up'::text, 'mcp'::text, 'mcp_chatgpt'::text, 'dashboard_chat'::text, 'owner_alert'::text])))
);

alter table sms_outbound_log add column if not exists id uuid not null default gen_random_uuid();
alter table sms_outbound_log add column if not exists business_id uuid;
alter table sms_outbound_log add column if not exists to_e164 text;
alter table sms_outbound_log add column if not exists from_e164 text;
alter table sms_outbound_log add column if not exists body text;
alter table sms_outbound_log add column if not exists source text;
alter table sms_outbound_log add column if not exists run_id uuid;
alter table sms_outbound_log add column if not exists flow_id uuid;
alter table sms_outbound_log add column if not exists telnyx_message_id text;
alter table sms_outbound_log add column if not exists created_at timestamp with time zone not null default now();
alter table sms_outbound_log add column if not exists channel text not null default 'sms'::text;
alter table sms_outbound_log add column if not exists scheduled_sms_id uuid;
alter table sms_outbound_log add column if not exists deleted_at timestamp with time zone;
alter table sms_outbound_log add column if not exists deleted_by uuid;
alter table sms_outbound_log add column if not exists destination_country text;

do $$ declare c record; begin
  for c in select conname from pg_constraint
            where conrelid = 'sms_outbound_log'::regclass and contype = 'c' loop
    execute format('alter table sms_outbound_log drop constraint %I', c.conname);
  end loop;
end $$;
alter table sms_outbound_log add constraint sms_outbound_log_channel_check CHECK ((channel = ANY (ARRAY['sms'::text, 'rcs'::text])));
alter table sms_outbound_log add constraint sms_outbound_log_source_check CHECK ((source = ANY (ARRAY['ai_flow'::text, 'agent_offer'::text, 'owner_notify'::text, 'owner_manual'::text, 'owner_scheduled'::text, 'api'::text, 'voice_follow_up'::text, 'mcp'::text, 'mcp_chatgpt'::text, 'dashboard_chat'::text, 'owner_alert'::text])));

create index if not exists sms_outbound_log_business_created_idx ON public.sms_outbound_log USING btree (business_id, created_at DESC);
create index if not exists sms_outbound_log_business_to_idx ON public.sms_outbound_log USING btree (business_id, to_e164, created_at DESC);
create index if not exists sms_outbound_log_deleted_idx ON public.sms_outbound_log USING btree (business_id, deleted_at DESC) WHERE (deleted_at IS NOT NULL);
create unique index if not exists sms_outbound_log_scheduled_idx ON public.sms_outbound_log USING btree (scheduled_sms_id) WHERE (scheduled_sms_id IS NOT NULL);

-- ── sms_rowboat_threads ─────────────────────────────────────────
create table if not exists sms_rowboat_threads (
  business_id uuid not null,
  customer_e164 text not null,
  rowboat_conversation_id text not null,
  rowboat_state jsonb,
  updated_at timestamp with time zone not null default now(),
  constraint sms_rowboat_threads_pkey PRIMARY KEY (business_id, customer_e164)
);

alter table sms_rowboat_threads add column if not exists business_id uuid;
alter table sms_rowboat_threads add column if not exists customer_e164 text;
alter table sms_rowboat_threads add column if not exists rowboat_conversation_id text;
alter table sms_rowboat_threads add column if not exists rowboat_state jsonb;
alter table sms_rowboat_threads add column if not exists updated_at timestamp with time zone not null default now();

do $$ declare c record; begin
  for c in select conname from pg_constraint
            where conrelid = 'sms_rowboat_threads'::regclass and contype = 'c' loop
    execute format('alter table sms_rowboat_threads drop constraint %I', c.conname);
  end loop;
end $$;

create index if not exists idx_sms_rowboat_threads_updated ON public.sms_rowboat_threads USING btree (updated_at DESC);

-- ── sms_owner_reply_prompts ─────────────────────────────────────
create table if not exists sms_owner_reply_prompts (
  id uuid not null default gen_random_uuid(),
  business_id uuid not null,
  customer_e164 text not null,
  inbound_job_id uuid,
  inbound_text text not null default ''::text,
  answered_at timestamp with time zone,
  reply_body text,
  reply_telnyx_message_id text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint sms_owner_reply_prompts_pkey PRIMARY KEY (id)
);

alter table sms_owner_reply_prompts add column if not exists id uuid not null default gen_random_uuid();
alter table sms_owner_reply_prompts add column if not exists business_id uuid;
alter table sms_owner_reply_prompts add column if not exists customer_e164 text;
alter table sms_owner_reply_prompts add column if not exists inbound_job_id uuid;
alter table sms_owner_reply_prompts add column if not exists inbound_text text not null default ''::text;
alter table sms_owner_reply_prompts add column if not exists answered_at timestamp with time zone;
alter table sms_owner_reply_prompts add column if not exists reply_body text;
alter table sms_owner_reply_prompts add column if not exists reply_telnyx_message_id text;
alter table sms_owner_reply_prompts add column if not exists created_at timestamp with time zone not null default now();
alter table sms_owner_reply_prompts add column if not exists updated_at timestamp with time zone not null default now();

do $$ declare c record; begin
  for c in select conname from pg_constraint
            where conrelid = 'sms_owner_reply_prompts'::regclass and contype = 'c' loop
    execute format('alter table sms_owner_reply_prompts drop constraint %I', c.conname);
  end loop;
end $$;

create index if not exists idx_sms_owner_reply_prompts_pending ON public.sms_owner_reply_prompts USING btree (business_id, created_at DESC) WHERE (answered_at IS NULL);
create unique index if not exists uq_sms_owner_reply_prompts_job ON public.sms_owner_reply_prompts USING btree (inbound_job_id) WHERE (inbound_job_id IS NOT NULL);

-- ── scheduled_sms ───────────────────────────────────────────────
create table if not exists scheduled_sms (
  id uuid not null default gen_random_uuid(),
  business_id uuid not null,
  to_e164 text not null,
  body text not null,
  send_at timestamp with time zone not null,
  status text not null default 'pending'::text,
  error text,
  telnyx_message_id text,
  created_at timestamp with time zone not null default now(),
  claimed_at timestamp with time zone,
  sent_at timestamp with time zone,
  constraint scheduled_sms_pkey PRIMARY KEY (id),
  constraint scheduled_sms_body_check CHECK (((char_length(body) >= 1) AND (char_length(body) <= 1600))),
  constraint scheduled_sms_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'sending'::text, 'sent'::text, 'canceled'::text, 'failed'::text])))
);

alter table scheduled_sms add column if not exists id uuid not null default gen_random_uuid();
alter table scheduled_sms add column if not exists business_id uuid;
alter table scheduled_sms add column if not exists to_e164 text;
alter table scheduled_sms add column if not exists body text;
alter table scheduled_sms add column if not exists send_at timestamp with time zone;
alter table scheduled_sms add column if not exists status text not null default 'pending'::text;
alter table scheduled_sms add column if not exists error text;
alter table scheduled_sms add column if not exists telnyx_message_id text;
alter table scheduled_sms add column if not exists created_at timestamp with time zone not null default now();
alter table scheduled_sms add column if not exists claimed_at timestamp with time zone;
alter table scheduled_sms add column if not exists sent_at timestamp with time zone;

do $$ declare c record; begin
  for c in select conname from pg_constraint
            where conrelid = 'scheduled_sms'::regclass and contype = 'c' loop
    execute format('alter table scheduled_sms drop constraint %I', c.conname);
  end loop;
end $$;
alter table scheduled_sms add constraint scheduled_sms_body_check CHECK (((char_length(body) >= 1) AND (char_length(body) <= 1600)));
alter table scheduled_sms add constraint scheduled_sms_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'sending'::text, 'sent'::text, 'canceled'::text, 'failed'::text])));

create index if not exists scheduled_sms_business_idx ON public.scheduled_sms USING btree (business_id, send_at DESC);
create index if not exists scheduled_sms_due_idx ON public.scheduled_sms USING btree (status, send_at);

-- ── notifications ───────────────────────────────────────────────
create table if not exists notifications (
  id uuid not null,
  business_id uuid not null,
  delivery_channel text not null,
  status text not null,
  payload jsonb not null,
  created_at timestamp with time zone not null default now(),
  read_at timestamp with time zone,
  kind text,
  summary text,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  read_by_actor text,
  constraint notifications_pkey PRIMARY KEY (id),
  constraint notifications_delivery_channel_check CHECK ((delivery_channel = ANY (ARRAY['sms'::text, 'email'::text, 'dashboard'::text, 'whatsapp'::text, 'slack'::text, 'telegram'::text, 'teams'::text, 'push'::text])))
);

alter table notifications add column if not exists id uuid;
alter table notifications add column if not exists business_id uuid;
alter table notifications add column if not exists delivery_channel text;
alter table notifications add column if not exists status text;
alter table notifications add column if not exists payload jsonb;
alter table notifications add column if not exists created_at timestamp with time zone not null default now();
alter table notifications add column if not exists read_at timestamp with time zone;
alter table notifications add column if not exists kind text;
alter table notifications add column if not exists summary text;
alter table notifications add column if not exists deleted_at timestamp with time zone;
alter table notifications add column if not exists deleted_by uuid;
alter table notifications add column if not exists read_by_actor text;

do $$ declare c record; begin
  for c in select conname from pg_constraint
            where conrelid = 'notifications'::regclass and contype = 'c' loop
    execute format('alter table notifications drop constraint %I', c.conname);
  end loop;
end $$;
alter table notifications add constraint notifications_delivery_channel_check CHECK ((delivery_channel = ANY (ARRAY['sms'::text, 'email'::text, 'dashboard'::text, 'whatsapp'::text, 'slack'::text, 'telegram'::text, 'teams'::text, 'push'::text])));

create index if not exists notifications_business_unread_idx ON public.notifications USING btree (business_id, created_at DESC) WHERE ((status = 'sent'::text) AND (read_at IS NULL));
create index if not exists notifications_deleted_idx ON public.notifications USING btree (business_id, deleted_at DESC) WHERE (deleted_at IS NOT NULL);

-- ── ai_flows ────────────────────────────────────────────────────
create table if not exists ai_flows (
  id uuid not null default gen_random_uuid(),
  business_id uuid not null,
  name text not null,
  enabled boolean not null default true,
  definition jsonb not null default '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  enabled_changed_at timestamp with time zone,
  deleted_at timestamp with time zone,
  deleted_by uuid,
  edit_source text,
  edit_actor text,
  constraint ai_flows_pkey PRIMARY KEY (id),
  constraint ai_flows_name_check CHECK (((length(TRIM(BOTH FROM name)) >= 1) AND (length(TRIM(BOTH FROM name)) <= 120)))
);

alter table ai_flows add column if not exists id uuid not null default gen_random_uuid();
alter table ai_flows add column if not exists business_id uuid;
alter table ai_flows add column if not exists name text;
alter table ai_flows add column if not exists enabled boolean not null default true;
alter table ai_flows add column if not exists definition jsonb not null default '{}'::jsonb;
alter table ai_flows add column if not exists created_by uuid;
alter table ai_flows add column if not exists created_at timestamp with time zone not null default now();
alter table ai_flows add column if not exists updated_at timestamp with time zone not null default now();
alter table ai_flows add column if not exists enabled_changed_at timestamp with time zone;
alter table ai_flows add column if not exists deleted_at timestamp with time zone;
alter table ai_flows add column if not exists deleted_by uuid;
alter table ai_flows add column if not exists edit_source text;
alter table ai_flows add column if not exists edit_actor text;

do $$ declare c record; begin
  for c in select conname from pg_constraint
            where conrelid = 'ai_flows'::regclass and contype = 'c' loop
    execute format('alter table ai_flows drop constraint %I', c.conname);
  end loop;
end $$;
alter table ai_flows add constraint ai_flows_name_check CHECK (((length(TRIM(BOTH FROM name)) >= 1) AND (length(TRIM(BOTH FROM name)) <= 120)));

create index if not exists ai_flows_business_enabled_idx ON public.ai_flows USING btree (business_id) WHERE enabled;
create index if not exists ai_flows_business_id_idx ON public.ai_flows USING btree (business_id);
create index if not exists ai_flows_deleted_idx ON public.ai_flows USING btree (business_id, deleted_at DESC) WHERE (deleted_at IS NOT NULL);

-- ── aiflow_url_memory ───────────────────────────────────────────
create table if not exists aiflow_url_memory (
  business_id uuid not null,
  memory_key text not null,
  url text not null,
  flow_id uuid,
  run_id uuid,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint aiflow_url_memory_pkey PRIMARY KEY (business_id, memory_key),
  constraint aiflow_url_memory_memory_key_check CHECK (((length(memory_key) >= 1) AND (length(memory_key) <= 32))),
  constraint aiflow_url_memory_url_check CHECK (((length(url) >= 1) AND (length(url) <= 4000)))
);

alter table aiflow_url_memory add column if not exists business_id uuid;
alter table aiflow_url_memory add column if not exists memory_key text;
alter table aiflow_url_memory add column if not exists url text;
alter table aiflow_url_memory add column if not exists flow_id uuid;
alter table aiflow_url_memory add column if not exists run_id uuid;
alter table aiflow_url_memory add column if not exists created_at timestamp with time zone not null default now();
alter table aiflow_url_memory add column if not exists updated_at timestamp with time zone not null default now();

do $$ declare c record; begin
  for c in select conname from pg_constraint
            where conrelid = 'aiflow_url_memory'::regclass and contype = 'c' loop
    execute format('alter table aiflow_url_memory drop constraint %I', c.conname);
  end loop;
end $$;
alter table aiflow_url_memory add constraint aiflow_url_memory_memory_key_check CHECK (((length(memory_key) >= 1) AND (length(memory_key) <= 32)));
alter table aiflow_url_memory add constraint aiflow_url_memory_url_check CHECK (((length(url) >= 1) AND (length(url) <= 4000)));

create index if not exists aiflow_url_memory_business_updated_idx ON public.aiflow_url_memory USING btree (business_id, updated_at DESC);

-- ── foreign keys between moved tables ─────────────────────────
alter table dashboard_chat_messages
  drop constraint if exists dashboard_chat_messages_thread_id_fkey;
alter table dashboard_chat_messages
  add constraint dashboard_chat_messages_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES dashboard_chat_threads(id) ON DELETE CASCADE;
alter table voice_call_transcript_turns
  drop constraint if exists voice_call_transcript_turns_transcript_id_fkey;
alter table voice_call_transcript_turns
  add constraint voice_call_transcript_turns_transcript_id_fkey FOREIGN KEY (transcript_id) REFERENCES voice_call_transcripts(id) ON DELETE CASCADE;
alter table voice_outbound_dial_log
  drop constraint if exists voice_outbound_dial_log_flow_id_fkey;
alter table voice_outbound_dial_log
  add constraint voice_outbound_dial_log_flow_id_fkey FOREIGN KEY (flow_id) REFERENCES ai_flows(id) ON DELETE CASCADE;

-- Applied-schema stamp (must stay the FINAL statement).
insert into residency_schema_meta (key, value) values ('generated_at', '2026-08-27T06:42:41.356Z')
  on conflict (key) do update set value = excluded.value;
