/**
 * The robots.txt we serve, built by hand rather than through Next's
 * `MetadataRoute.Robots`.
 *
 * Two reasons for the hand-built file. `Content-Signal` is not expressible
 * through the typed metadata API, and this file is now the ONLY statement of
 * our crawl policy: Cloudflare's "Managed robots.txt" used to prepend a block
 * here, and it was turned off because it CREATES a file where the origin
 * serves none, which left the apex with a standalone robots.txt carrying none
 * of our `Disallow` rules and no `Sitemap:` line.
 *
 * Same shape as src/app/llms.txt/route.ts: a pure builder plus a thin route.
 */

import { AI_ANSWER_CRAWLER_TOKENS, AI_TRAINING_CRAWLER_TOKENS } from "./ai-crawlers";
import { SITE_URL } from "./site-url";

/** Authenticated and machine surfaces, never for crawlers. */
export const ROBOTS_DISALLOW = ["/dashboard", "/admin", "/api"];

/**
 * Cloudflare's Content Signals vocabulary, preserved from the managed block
 * this file replaced. Advisory rather than enforced, so the `Disallow`
 * groups below are what actually holds: search indexing yes, AI grounding
 * and citation yes, corpus training no.
 */
const CONTENT_SIGNAL = "search=yes,ai-input=yes,ai-train=no";

function group(agents: string[], lines: string[]): string[] {
  return [...agents.map((a) => `User-agent: ${a}`), ...lines, ""];
}

export function buildRobotsTxt(): string {
  const standardRules = ["Allow: /", ...ROBOTS_DISALLOW.map((p) => `Disallow: ${p}`)];

  return [
    "# newcoworker.com robots.txt",
    "# Generated by src/lib/marketing/robots-txt.ts. Edit there, not here.",
    "",
    ...group(["*"], [`Content-Signal: ${CONTENT_SIGNAL}`, ...standardRules]),
    "# AI assistants that answer questions and cite sources. Listed explicitly",
    "# because a crawler matching its own group ignores `*` entirely, so the",
    "# disallows are repeated rather than inherited.",
    ...group(AI_ANSWER_CRAWLER_TOKENS, standardRules),
    "# Model-training crawlers. Our content is for answering a buyer's",
    "# question, not for a training corpus.",
    ...group(AI_TRAINING_CRAWLER_TOKENS, ["Disallow: /"]),
    `Sitemap: ${SITE_URL}/sitemap.xml`,
    ""
  ].join("\n");
}
