/**
 * Prefilled Letter of Authorization (LOA) PDF for BYON port-ins.
 *
 * Carriers require a signed LOA naming the number, the account holder, and
 * the person authorizing the port. The wizard prefills everything it already
 * collected, the owner downloads → signs → re-uploads — the same flow
 * Telnyx's own portal uses. Keeping generation server-side means the
 * document always matches what we submit on the porting order.
 */

import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { formatDid } from "@/lib/telnyx/format";

export type LoaFields = {
  phoneE164: string;
  /** Business name exactly as on the losing carrier's account. */
  entityName: string;
  /** Person authorized to port (whose signature goes on the line). */
  authorizedName: string;
  accountNumber: string;
  serviceAddress: {
    street: string;
    extended?: string;
    city: string;
    state: string;
    zip: string;
  };
  /** Losing carrier's name, when the owner provided it. */
  carrierName?: string;
};

const PAGE_WIDTH = 612; // US Letter
const PAGE_HEIGHT = 792;
const MARGIN = 64;
const BODY_SIZE = 11;
const LINE_HEIGHT = 18;

/** Generate the prefilled LOA as PDF bytes. */
export async function generateLoaPdf(fields: LoaFields): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  let y = PAGE_HEIGHT - MARGIN;

  const drawText = (
    text: string,
    opts: { bold?: boolean; size?: number; gapAfter?: number } = {}
  ) => {
    page.drawText(text, {
      x: MARGIN,
      y,
      size: opts.size ?? BODY_SIZE,
      font: opts.bold ? bold : font,
      color: rgb(0.1, 0.1, 0.12)
    });
    y -= (opts.size ?? BODY_SIZE) + (opts.gapAfter ?? LINE_HEIGHT - BODY_SIZE);
  };

  const drawField = (label: string, value: string) => {
    page.drawText(label, { x: MARGIN, y, size: BODY_SIZE, font: bold, color: rgb(0.1, 0.1, 0.12) });
    page.drawText(value, {
      x: MARGIN + 190,
      y,
      size: BODY_SIZE,
      font,
      color: rgb(0.1, 0.1, 0.12)
    });
    y -= LINE_HEIGHT;
  };

  drawText("LETTER OF AUTHORIZATION", { bold: true, size: 16, gapAfter: 10 });
  drawText("Telephone Number Port Request", { size: 12, gapAfter: 22 });

  const addressLine2 = [
    fields.serviceAddress.city,
    `${fields.serviceAddress.state} ${fields.serviceAddress.zip}`
  ].join(", ");

  drawField("Telephone number:", formatDid(fields.phoneE164));
  drawField("Current carrier:", fields.carrierName?.trim() || "(current service provider)");
  drawField("Account number:", fields.accountNumber);
  drawField("Business name:", fields.entityName);
  drawField("Service address:", fields.serviceAddress.street);
  if (fields.serviceAddress.extended?.trim()) {
    drawField("", fields.serviceAddress.extended.trim());
  }
  drawField("", addressLine2);
  y -= 12;

  const paragraphs = [
    `I, ${fields.authorizedName}, certify that I am authorized to act on behalf of`,
    `${fields.entityName} for the telephone number listed above. I hereby authorize`,
    "Telnyx LLC and its agents to act on my behalf to port the listed telephone",
    "number from the current service provider to Telnyx LLC, and to obtain any",
    "information required to complete this port, including customer service",
    "records. I understand that porting this number may end the services",
    "associated with it at my current provider.",
    "",
    "This authorization remains valid for 90 days from the signature date below."
  ];
  for (const line of paragraphs) {
    drawText(line);
  }
  y -= 30;

  const drawSignatureLine = (label: string) => {
    page.drawLine({
      start: { x: MARGIN, y },
      end: { x: MARGIN + 220, y },
      thickness: 0.8,
      color: rgb(0.1, 0.1, 0.12)
    });
    page.drawText(label, {
      x: MARGIN,
      y: y - 14,
      size: 9,
      font,
      color: rgb(0.35, 0.35, 0.38)
    });
    y -= 48;
  };

  drawSignatureLine(`Signature (${fields.authorizedName})`);
  drawSignatureLine("Date");

  page.drawText(
    "Generated by New Coworker — sign and upload with a recent bill to submit your port.",
    {
      x: MARGIN,
      y: MARGIN - 24,
      size: 8,
      font,
      color: rgb(0.45, 0.45, 0.48)
    }
  );

  return doc.save();
}
