export const BUSINESS_TYPE_LABELS = {
  real_estate: "Real Estate",
  hair_salons: "Hair Salons",
  massage_therapy: "Massage Therapy",
  pet_services: "Pet Services",
  auto_repair: "Auto Repair",
  hvac_services: "HVAC Services",
  plumbing: "Plumbing",
  landscaping: "Landscaping",
  pool_services: "Pool Services",
  cleaning_services: "Cleaning Services",
  personal_training: "Personal Training",
  photography: "Photography",
  web_design: "Web Design",
  consulting: "Consulting",
  accounting: "Accounting",
  legal_services: "Legal Services",
  dental_care: "Dental Care",
  chiropractic: "Chiropractic",
  medical_practice: "Medical Practice",
  physical_therapy: "Physical Therapy",
  med_spa: "Med Spa",
  veterinary: "Veterinary",
  handyman_service: "Handyman Service",
  painting: "Painting",
  roofing: "Roofing",
  pest_control: "Pest Control",
  solar_services: "Solar Services",
  garage_door_services: "Garage Door Services",
  beauty_spa: "Beauty Spa",
  wellness_services: "Wellness Services",
  event_planning: "Event Planning",
  general_contractors: "General Contractors",
  electrical_contractors: "Electrical Contractors",
  custom_carpentry: "Custom Carpentry",
  appliance_repair: "Appliance Repair",
  catering: "Catering",
  it_support: "IT Support",
  tutoring: "Tutoring",
  carpet_cleaning: "Carpet Cleaning",
  moving_services: "Moving Services",
  dj_services: "DJ Services",
  tax_preparation: "Tax Preparation",
  insurance_agency: "Insurance Agency",
  mortgage_brokerage: "Mortgage Brokerage",
  yoga_classes: "Yoga Classes",
  escape_rooms: "Escape Rooms",
  wine_tasting: "Wine Tasting",
  cooking_classes: "Cooking Classes",
  art_studios: "Art Studios",
  dance_studios: "Dance Studios",
  music_lessons: "Music Lessons",
  adventure_tours: "Adventure Tours",
  boat_charters: "Boat Charters",
  food_tours: "Food Tours",
  museums: "Museums",
  aquariums: "Aquariums",
  theme_parks: "Theme Parks",
  zip_lines: "Zip Lines",
  paintball: "Paintball",
  bowling_alleys: "Bowling Alleys",
  mini_golf: "Mini Golf",
  arcades: "Arcades",
  workshops: "Workshops",
  retreats: "Retreats",
  equipment_rentals: "Equipment Rentals",
  party_rentals: "Party Rentals",
  event_rentals: "Event Rentals",
  photo_booth_rentals: "Photo Booth Rentals",
  bike_rentals: "Bike Rentals",
  kayak_rentals: "Kayak Rentals",
  camping_gear_rentals: "Camping Gear Rentals",
  bounce_house_rentals: "Bounce House Rentals",
  boat_rentals: "Boat Rentals",
  ghost_tours: "Ghost Tours",
  laser_tag: "Laser Tag",
  comedy_clubs: "Comedy Clubs",
  festivals: "Festivals",
  farmers_markets: "Farmers Markets",
  boutiques: "Boutiques",
  jewelry_stores: "Jewelry Stores",
  electronics: "Electronics",
  bookstores: "Bookstores",
  art_galleries: "Art Galleries",
  craft_stores: "Craft Stores",
  antique_shops: "Antique Shops",
  toy_stores: "Toy Stores",
  sports_equipment: "Sports Equipment",
  outdoor_gear: "Outdoor Gear",
  home_decor: "Home Decor",
  furniture_stores: "Furniture Stores",
  bakeries: "Bakeries",
  coffee_shops: "Coffee Shops",
  wine_shops: "Wine Shops",
  specialty_foods: "Specialty Foods",
  cosmetics: "Cosmetics",
  pet_supplies: "Pet Supplies",
  plant_nurseries: "Plant Nurseries",
  hardware_stores: "Hardware Stores",
  gift_shops: "Gift Shops",
  clothing: "Clothing",
  local_artisans: "Local Artisans",
  tool_rental: "Tool Rental",
  construction_equipment: "Construction Equipment",
  medical_equipment_rentals: "Medical Equipment Rentals",
  audiovisual_rentals: "Audiovisual Rentals",
  costume_rentals: "Costume Rentals",
  furniture_rentals: "Furniture Rentals",
  sports_equipment_rentals: "Sports Equipment Rentals",
  other: "Other"
} as const;

export type BusinessType = keyof typeof BUSINESS_TYPE_LABELS;

export const DEFAULT_BUSINESS_TYPE: BusinessType = "real_estate";

export const BUSINESS_TYPE_OPTIONS = Object.entries(BUSINESS_TYPE_LABELS).map(([value, label]) => ({
  value: value as BusinessType,
  label
}));
