import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/lib/supabase/server", () => ({
  createSupabaseServiceClient: vi.fn()
}));
vi.mock("@/lib/db/businesses", () => ({
  getBusiness: vi.fn()
}));
vi.mock("@/lib/documents/db", () => ({
  countBusinessDocuments: vi.fn(),
  deleteBusinessDocument: vi.fn(async () => undefined),
  insertBusinessDocument: vi.fn()
}));
vi.mock("@/lib/documents/render-pdf", () => ({
  renderHtmlToPdf: vi.fn()
}));

import { saveAgentRunArtifact } from "@/lib/agents/save-artifact";
import { createSupabaseServiceClient } from "@/lib/supabase/server";
import { getBusiness } from "@/lib/db/businesses";
import {
  countBusinessDocuments,
  deleteBusinessDocument,
  insertBusinessDocument
} from "@/lib/documents/db";
import { renderHtmlToPdf } from "@/lib/documents/render-pdf";

const BIZ = "00000000-0000-0000-0000-000000000001";

const RUN = {
  output_md: "# Comparison\n\n| a | b |",
  output_filename: "quotes.md",
  output_mime_type: "text/markdown",
  input_filename: "quotes.pdf"
};

function makeDb(opts: { uploadError?: { message: string } | null; removeError?: { message: string } | null } = {}) {
  const uploads: Array<{ path: string; contentType: string; bytes: Buffer }> = [];
  const removes: string[][] = [];
  const db = {
    storage: {
      from: () => ({
        upload: async (path: string, bytes: Buffer, meta: { contentType: string }) => {
          uploads.push({ path, contentType: meta.contentType, bytes });
          return { error: opts.uploadError ?? null };
        },
        remove: async (paths: string[]) => {
          removes.push(paths);
          return { error: opts.removeError ?? null };
        }
      })
    }
  };
  return { db, uploads, removes };
}

type Client = Awaited<ReturnType<typeof createSupabaseServiceClient>>;

beforeEach(() => {
  vi.clearAllMocks();
  vi.mocked(getBusiness).mockResolvedValue({ id: BIZ, tier: "standard" } as never);
  vi.mocked(countBusinessDocuments).mockResolvedValue(0);
  vi.mocked(insertBusinessDocument).mockImplementation(
    async (row) => ({ ...row } as never)
  );
});

describe("saveAgentRunArtifact", () => {
  it("saves the artifact as a document (explicit title, explicit client)", async () => {
    const { db, uploads } = makeDb();
    const result = await saveAgentRunArtifact(
      { businessId: BIZ, run: RUN, agentName: "Quote comparison", title: "July quotes", audience: "staff" },
      db as unknown as Client
    );
    expect(result.ok).toBe(true);
    if (result.ok) expect(result.document.title).toBe("July quotes");
    expect(uploads).toHaveLength(1);
    expect(uploads[0].contentType).toBe("text/markdown");
    const inserted = vi.mocked(insertBusinessDocument).mock.calls[0][0];
    expect(inserted).toMatchObject({
      business_id: BIZ,
      category: "generated",
      audience: "staff",
      status: "ready"
    });
    expect(inserted.summary).toContain('Generated by the "Quote comparison" agent');
    expect(inserted.summary).toContain("quotes.pdf");
  });

  it("defaults the title from the artifact filename, then the agent name", async () => {
    const { db } = makeDb();
    const fromFilename = await saveAgentRunArtifact(
      { businessId: BIZ, run: RUN, agentName: "A", audience: "staff" },
      db as unknown as Client
    );
    expect(fromFilename.ok && fromFilename.document.title).toBe("quotes");

    const fromAgent = await saveAgentRunArtifact(
      {
        businessId: BIZ,
        run: { ...RUN, output_filename: "" },
        agentName: "Quote agent",
        audience: "staff"
      },
      db as unknown as Client
    );
    expect(fromAgent.ok && fromAgent.document.title).toBe("Quote agent output");
  });

  it("falls back to the service client when none is passed and defaults the mime", async () => {
    const { db, uploads } = makeDb();
    vi.mocked(createSupabaseServiceClient).mockResolvedValue(db as never);
    const result = await saveAgentRunArtifact({
      businessId: BIZ,
      run: { ...RUN, output_mime_type: "", input_filename: "" },
      agentName: "A",
      audience: "both"
    });
    expect(result.ok).toBe(true);
    expect(uploads[0].contentType).toBe("text/markdown");
    const inserted = vi.mocked(insertBusinessDocument).mock.calls[0][0];
    expect(inserted.audience).toBe("both");
    expect(inserted.summary).toBe('Generated by the "A" agent.');
  });

  it("typesets PDF and DOCX artifacts into real bytes for storage", async () => {
    const { db, uploads } = makeDb();
    const pdf = await saveAgentRunArtifact(
      {
        businessId: BIZ,
        run: { ...RUN, output_filename: "quotes.pdf", output_mime_type: "application/pdf" },
        agentName: "A",
        audience: "staff"
      },
      db as unknown as Client
    );
    expect(pdf.ok).toBe(true);
    expect(uploads[0].contentType).toBe("application/pdf");
    expect(uploads[0].bytes.subarray(0, 5).toString("ascii")).toBe("%PDF-");

    const docxMime = "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
    const docx = await saveAgentRunArtifact(
      {
        businessId: BIZ,
        run: { ...RUN, output_filename: "quotes.docx", output_mime_type: docxMime },
        agentName: "A",
        audience: "staff"
      },
      db as unknown as Client
    );
    expect(docx.ok).toBe(true);
    expect(uploads[1].contentType).toBe(docxMime);
    expect(uploads[1].bytes.subarray(0, 2).toString("ascii")).toBe("PK");

    // content_md stays the markdown artifact — knowledge lookup reads text.
    const inserted = vi.mocked(insertBusinessDocument).mock.calls[0][0];
    expect(inserted.mime_type).toBe("application/pdf");
    expect(inserted.content_md).toBe(RUN.output_md);
  });

  it("renders re-typeset HTML artifacts via the sidecar and files their text", async () => {
    vi.mocked(renderHtmlToPdf).mockResolvedValue({
      ok: true,
      pdf: Buffer.from("%PDF-1.7 sidecar")
    });
    const { db, uploads } = makeDb();
    const htmlRun = {
      output_md:
        "<!DOCTYPE html><html><body><h1>Policy</h1><p>Premium: $999</p></body></html>",
      output_filename: "policy.pdf",
      output_mime_type: "application/pdf",
      input_filename: "policy.pdf"
    };
    const result = await saveAgentRunArtifact(
      { businessId: BIZ, run: htmlRun, agentName: "Re-typesetter", audience: "staff" },
      db as unknown as Client
    );
    expect(result.ok).toBe(true);
    expect(uploads[0].bytes.toString("ascii")).toBe("%PDF-1.7 sidecar");
    const inserted = vi.mocked(insertBusinessDocument).mock.calls[0][0];
    // Knowledge lookup reads text, so the filed content_md is the visible
    // text of the HTML, not the markup.
    expect(inserted.content_md).toContain("Premium: $999");
    expect(inserted.content_md).not.toContain("<h1>");
  });

  it("refuses cleanly when the re-typeset renderer is unavailable", async () => {
    vi.mocked(renderHtmlToPdf).mockResolvedValue({ ok: false, error: "not_configured" });
    const { db, uploads } = makeDb();
    const result = await saveAgentRunArtifact(
      {
        businessId: BIZ,
        run: {
          output_md: "<!DOCTYPE html><html><body>x</body></html>",
          output_filename: "policy.pdf",
          output_mime_type: "application/pdf",
          input_filename: "policy.pdf"
        },
        agentName: "Re-typesetter",
        audience: "staff"
      },
      db as unknown as Client
    );
    expect(result).toEqual({
      ok: false,
      error: "storage_failed",
      detail: "PDF re-typesetting is not configured on this platform"
    });
    expect(uploads).toHaveLength(0);
    expect(insertBusinessDocument).not.toHaveBeenCalled();
  });

  it("refuses a run with no output", async () => {
    const { db } = makeDb();
    const result = await saveAgentRunArtifact(
      { businessId: BIZ, run: { ...RUN, output_md: "" }, agentName: "A", audience: "staff" },
      db as unknown as Client
    );
    expect(result).toMatchObject({ ok: false, error: "no_output" });
  });

  it("refuses when the business is missing", async () => {
    vi.mocked(getBusiness).mockResolvedValue(null as never);
    const { db } = makeDb();
    const result = await saveAgentRunArtifact(
      { businessId: BIZ, run: RUN, agentName: "A", audience: "staff" },
      db as unknown as Client
    );
    expect(result).toMatchObject({ ok: false, error: "business_not_found" });
  });

  it("refuses at the tier document cap before writing anything", async () => {
    vi.mocked(countBusinessDocuments).mockResolvedValue(10_000);
    const { db, uploads } = makeDb();
    const result = await saveAgentRunArtifact(
      { businessId: BIZ, run: RUN, agentName: "A", audience: "staff" },
      db as unknown as Client
    );
    expect(result).toMatchObject({ ok: false, error: "document_limit" });
    expect(uploads).toHaveLength(0);
  });

  it("reports a storage upload failure", async () => {
    const { db } = makeDb({ uploadError: { message: "bucket down" } });
    const result = await saveAgentRunArtifact(
      { businessId: BIZ, run: RUN, agentName: "A", audience: "staff" },
      db as unknown as Client
    );
    expect(result).toMatchObject({ ok: false, error: "storage_failed" });
    expect(insertBusinessDocument).not.toHaveBeenCalled();
  });

  it("compensates the uploaded object when the insert throws (and logs a failed cleanup)", async () => {
    vi.mocked(insertBusinessDocument).mockRejectedValue(new Error("insert broke"));
    const cleanupOk = makeDb();
    await expect(
      saveAgentRunArtifact(
        { businessId: BIZ, run: RUN, agentName: "A", audience: "staff" },
        cleanupOk.db as unknown as Client
      )
    ).rejects.toThrow("insert broke");
    expect(cleanupOk.removes).toHaveLength(1);

    const cleanupFails = makeDb({ removeError: { message: "remove broke" } });
    await expect(
      saveAgentRunArtifact(
        { businessId: BIZ, run: RUN, agentName: "A", audience: "staff" },
        cleanupFails.db as unknown as Client
      )
    ).rejects.toThrow("insert broke");
    expect(cleanupFails.removes).toHaveLength(1);
  });

  it("rolls back when the serial re-check lands over the cap", async () => {
    vi.mocked(countBusinessDocuments)
      .mockResolvedValueOnce(0)
      .mockResolvedValueOnce(10_000);
    const { db, removes } = makeDb();
    const result = await saveAgentRunArtifact(
      { businessId: BIZ, run: RUN, agentName: "A", audience: "staff" },
      db as unknown as Client
    );
    expect(result).toMatchObject({ ok: false, error: "document_limit" });
    expect(deleteBusinessDocument).toHaveBeenCalledTimes(1);
    expect(removes).toHaveLength(1);
  });

  it("still reports the cap when the over-cap object cleanup fails", async () => {
    vi.mocked(countBusinessDocuments)
      .mockResolvedValueOnce(0)
      .mockResolvedValueOnce(10_000);
    const { db } = makeDb({ removeError: { message: "remove broke" } });
    const result = await saveAgentRunArtifact(
      { businessId: BIZ, run: RUN, agentName: "A", audience: "staff" },
      db as unknown as Client
    );
    expect(result).toMatchObject({ ok: false, error: "document_limit" });
  });
});
