import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/lib/supabase/server", () => ({
  createSupabaseServiceClient: vi.fn()
}));
vi.mock("@/lib/db/businesses", () => ({
  getBusiness: vi.fn()
}));
vi.mock("@/lib/documents/db", () => ({
  countBusinessDocuments: vi.fn(),
  deleteBusinessDocument: vi.fn(async () => undefined),
  insertBusinessDocument: vi.fn()
}));

import { saveAgentRunArtifact } from "@/lib/agents/save-artifact";
import { createSupabaseServiceClient } from "@/lib/supabase/server";
import { getBusiness } from "@/lib/db/businesses";
import {
  countBusinessDocuments,
  deleteBusinessDocument,
  insertBusinessDocument
} from "@/lib/documents/db";

const BIZ = "00000000-0000-0000-0000-000000000001";

const RUN = {
  output_md: "# Comparison\n\n| a | b |",
  output_filename: "quotes.md",
  output_mime_type: "text/markdown",
  input_filename: "quotes.pdf"
};

function makeDb(opts: { uploadError?: { message: string } | null; removeError?: { message: string } | null } = {}) {
  const uploads: Array<{ path: string; contentType: string }> = [];
  const removes: string[][] = [];
  const db = {
    storage: {
      from: () => ({
        upload: async (path: string, _bytes: Buffer, meta: { contentType: string }) => {
          uploads.push({ path, contentType: meta.contentType });
          return { error: opts.uploadError ?? null };
        },
        remove: async (paths: string[]) => {
          removes.push(paths);
          return { error: opts.removeError ?? null };
        }
      })
    }
  };
  return { db, uploads, removes };
}

type Client = Awaited<ReturnType<typeof createSupabaseServiceClient>>;

beforeEach(() => {
  vi.clearAllMocks();
  vi.mocked(getBusiness).mockResolvedValue({ id: BIZ, tier: "standard" } as never);
  vi.mocked(countBusinessDocuments).mockResolvedValue(0);
  vi.mocked(insertBusinessDocument).mockImplementation(
    async (row) => ({ ...row } as never)
  );
});

describe("saveAgentRunArtifact", () => {
  it("saves the artifact as a document (explicit title, explicit client)", async () => {
    const { db, uploads } = makeDb();
    const result = await saveAgentRunArtifact(
      { businessId: BIZ, run: RUN, agentName: "Quote comparison", title: "July quotes", audience: "staff" },
      db as unknown as Client
    );
    expect(result.ok).toBe(true);
    if (result.ok) expect(result.document.title).toBe("July quotes");
    expect(uploads).toHaveLength(1);
    expect(uploads[0].contentType).toBe("text/markdown");
    const inserted = vi.mocked(insertBusinessDocument).mock.calls[0][0];
    expect(inserted).toMatchObject({
      business_id: BIZ,
      category: "generated",
      audience: "staff",
      status: "ready"
    });
    expect(inserted.summary).toContain('Generated by the "Quote comparison" agent');
    expect(inserted.summary).toContain("quotes.pdf");
  });

  it("defaults the title from the artifact filename, then the agent name", async () => {
    const { db } = makeDb();
    const fromFilename = await saveAgentRunArtifact(
      { businessId: BIZ, run: RUN, agentName: "A", audience: "staff" },
      db as unknown as Client
    );
    expect(fromFilename.ok && fromFilename.document.title).toBe("quotes");

    const fromAgent = await saveAgentRunArtifact(
      {
        businessId: BIZ,
        run: { ...RUN, output_filename: "" },
        agentName: "Quote agent",
        audience: "staff"
      },
      db as unknown as Client
    );
    expect(fromAgent.ok && fromAgent.document.title).toBe("Quote agent output");
  });

  it("falls back to the service client when none is passed and defaults the mime", async () => {
    const { db, uploads } = makeDb();
    vi.mocked(createSupabaseServiceClient).mockResolvedValue(db as never);
    const result = await saveAgentRunArtifact({
      businessId: BIZ,
      run: { ...RUN, output_mime_type: "", input_filename: "" },
      agentName: "A",
      audience: "both"
    });
    expect(result.ok).toBe(true);
    expect(uploads[0].contentType).toBe("text/markdown");
    const inserted = vi.mocked(insertBusinessDocument).mock.calls[0][0];
    expect(inserted.audience).toBe("both");
    expect(inserted.summary).toBe('Generated by the "A" agent.');
  });

  it("refuses a run with no output", async () => {
    const { db } = makeDb();
    const result = await saveAgentRunArtifact(
      { businessId: BIZ, run: { ...RUN, output_md: "" }, agentName: "A", audience: "staff" },
      db as unknown as Client
    );
    expect(result).toMatchObject({ ok: false, error: "no_output" });
  });

  it("refuses when the business is missing", async () => {
    vi.mocked(getBusiness).mockResolvedValue(null as never);
    const { db } = makeDb();
    const result = await saveAgentRunArtifact(
      { businessId: BIZ, run: RUN, agentName: "A", audience: "staff" },
      db as unknown as Client
    );
    expect(result).toMatchObject({ ok: false, error: "business_not_found" });
  });

  it("refuses at the tier document cap before writing anything", async () => {
    vi.mocked(countBusinessDocuments).mockResolvedValue(10_000);
    const { db, uploads } = makeDb();
    const result = await saveAgentRunArtifact(
      { businessId: BIZ, run: RUN, agentName: "A", audience: "staff" },
      db as unknown as Client
    );
    expect(result).toMatchObject({ ok: false, error: "document_limit" });
    expect(uploads).toHaveLength(0);
  });

  it("reports a storage upload failure", async () => {
    const { db } = makeDb({ uploadError: { message: "bucket down" } });
    const result = await saveAgentRunArtifact(
      { businessId: BIZ, run: RUN, agentName: "A", audience: "staff" },
      db as unknown as Client
    );
    expect(result).toMatchObject({ ok: false, error: "storage_failed" });
    expect(insertBusinessDocument).not.toHaveBeenCalled();
  });

  it("compensates the uploaded object when the insert throws (and logs a failed cleanup)", async () => {
    vi.mocked(insertBusinessDocument).mockRejectedValue(new Error("insert broke"));
    const cleanupOk = makeDb();
    await expect(
      saveAgentRunArtifact(
        { businessId: BIZ, run: RUN, agentName: "A", audience: "staff" },
        cleanupOk.db as unknown as Client
      )
    ).rejects.toThrow("insert broke");
    expect(cleanupOk.removes).toHaveLength(1);

    const cleanupFails = makeDb({ removeError: { message: "remove broke" } });
    await expect(
      saveAgentRunArtifact(
        { businessId: BIZ, run: RUN, agentName: "A", audience: "staff" },
        cleanupFails.db as unknown as Client
      )
    ).rejects.toThrow("insert broke");
    expect(cleanupFails.removes).toHaveLength(1);
  });

  it("rolls back when the serial re-check lands over the cap", async () => {
    vi.mocked(countBusinessDocuments)
      .mockResolvedValueOnce(0)
      .mockResolvedValueOnce(10_000);
    const { db, removes } = makeDb();
    const result = await saveAgentRunArtifact(
      { businessId: BIZ, run: RUN, agentName: "A", audience: "staff" },
      db as unknown as Client
    );
    expect(result).toMatchObject({ ok: false, error: "document_limit" });
    expect(deleteBusinessDocument).toHaveBeenCalledTimes(1);
    expect(removes).toHaveLength(1);
  });

  it("still reports the cap when the over-cap object cleanup fails", async () => {
    vi.mocked(countBusinessDocuments)
      .mockResolvedValueOnce(0)
      .mockResolvedValueOnce(10_000);
    const { db } = makeDb({ removeError: { message: "remove broke" } });
    const result = await saveAgentRunArtifact(
      { businessId: BIZ, run: RUN, agentName: "A", audience: "staff" },
      db as unknown as Client
    );
    expect(result).toMatchObject({ ok: false, error: "document_limit" });
  });
});
