/**
 * The 404 page's inlined logo (src/app/inline-logo.ts, generated by
 * scripts/generate-inline-logo.ts).
 *
 * Two things are being protected here, both of which are silent when broken:
 *
 * 1. Drift. The constant is a build artifact of `public/logo.png` committed as
 *    source, so swapping the brand mark without re-running the generator would
 *    leave the 404 showing the OLD logo forever, with nothing failing. The
 *    similarity check below catches that.
 * 2. The fan-out itself. Rendering that logo through `next/image` is what made
 *    one bot request for a junk URL cost three edge requests, and it is a
 *    one-line change for someone to "fix" the raw `<img>` back into an
 *    `<Image>`. So the page source is asserted directly.
 */
import { readFileSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";
import { describe, expect, it } from "vitest";

import { INLINE_LOGO_DATA_URI, INLINE_LOGO_PX } from "@/app/inline-logo";

const SOURCE_LOGO = path.join(process.cwd(), "public/logo.png");
const INLINED_PAGES = [
  "src/app/not-found.tsx",
  "src/app/error.tsx"
].map((p) => path.join(process.cwd(), p));

const PREFIX = "data:image/png;base64,";

/**
 * The whole point of inlining is that the bytes ride along in every 404's
 * HTML, and that HTML is never CDN-cached (next-intl reads cookies/headers, so
 * the page renders dynamically). A fat regeneration would quietly turn a win
 * into a regression, so the ceiling is asserted, generously above the ~674
 * bytes the current recipe produces.
 */
const MAX_PNG_BYTES = 2_048;

const decoded = Buffer.from(INLINE_LOGO_DATA_URI.slice(PREFIX.length), "base64");

/**
 * Mean absolute greyscale difference at 64x64, which is a blunt instrument but
 * a decisive one here: measured against the real source it scores ~3, and
 * against wrong artwork (the same logo flipped, rotated, or a flat fill of the
 * background colour) it scores 31 to 48. Ten sits far from both.
 *
 * Pixel-exact comparison is deliberately avoided: the encoder is a dependency,
 * and a sharp upgrade re-quantising by a shade must not fail this suite.
 */
async function meanGreyscaleDiff(a: Buffer, b: Buffer): Promise<number> {
  const [x, y] = await Promise.all(
    [a, b].map((buf) =>
      sharp(buf).greyscale().resize(64, 64, { fit: "fill" }).raw().toBuffer()
    )
  );
  let total = 0;
  for (let i = 0; i < x.length; i++) total += Math.abs(x[i] - y[i]);
  return total / x.length;
}

describe("inline 404 logo", () => {
  it("is a base64 PNG data URI", () => {
    expect(INLINE_LOGO_DATA_URI.startsWith(PREFIX)).toBe(true);
    // PNG magic number, proving the base64 actually decodes to what it claims.
    expect([...decoded.subarray(0, 4)]).toEqual([0x89, 0x50, 0x4e, 0x47]);
  });

  it("stays small enough to be cheaper than the request it replaces", () => {
    expect(decoded.byteLength).toBeLessThanOrEqual(MAX_PNG_BYTES);
  });

  it("is encoded at 2x the 48px box the page renders it in", async () => {
    const meta = await sharp(decoded).metadata();
    expect(meta.width).toBe(INLINE_LOGO_PX);
    expect(meta.height).toBe(INLINE_LOGO_PX);
    expect(INLINE_LOGO_PX).toBe(96);
  });

  it("still shows the current brand mark, so a logo swap cannot go unnoticed", async () => {
    const diff = await meanGreyscaleDiff(decoded, readFileSync(SOURCE_LOGO));
    expect(diff).toBeLessThan(10);
  });

  it("rejects wrong artwork rather than passing everything", async () => {
    // Guards the guard: if the threshold above were ever loosened into
    // meaninglessness, this fails too.
    const flipped = await sharp(readFileSync(SOURCE_LOGO)).flop().png().toBuffer();
    const diff = await meanGreyscaleDiff(decoded, flipped);
    expect(diff).toBeGreaterThan(10);
  });

  it("keeps the 404 and error pages off the image optimizer", () => {
    // Both render when something is already wrong (a junk URL, a crash), so
    // neither may depend on `/_next/image` or `/api/brand-logo`; that was the
    // fan-out behind the Aug 3 2026 usage-anomaly alert.
    for (const pagePath of INLINED_PAGES) {
      const page = readFileSync(pagePath, "utf8");
      expect(page, pagePath).not.toMatch(/from "next\/image"/);
      expect(page, pagePath).toContain("INLINE_LOGO_DATA_URI");
    }
  });
});
