/**
 * Pure slot math for the public booking page.
 *
 * Given real busy blocks (provider free/busy), the business-hours windows,
 * the page's policy knobs, and (optionally) the team roster's schedules and
 * time off, produce the bookable slot starts on a 30-minute business-local
 * grid. No I/O: the service layer fetches inputs, this module decides.
 *
 * DST rule (the BizBlasts lesson, DST_BUG_FIX_SUMMARY.md): a slot's end is
 * ALWAYS start + elapsed duration minutes. Candidates are generated by
 * elapsed-time stepping and classified in the business timezone with
 * `localClock`, so slot generation and booking creation can never disagree
 * about an end time across a DST transition.
 */

import {
  isWithinWeeklyWindows,
  localClock,
  parseHmToMinutes,
  parseWeeklyWindows
} from "../../../supabase/functions/_shared/ai_flows/engine";
import type { BusinessHours } from "@/lib/business-profile/profile";

export type BusyBlock = { start: Date; end: Date };

export type PublicSlotPolicy = {
  minNoticeMinutes: number;
  maxAdvanceDays: number;
  bufferMinutes: number;
  /** Null = uncapped. */
  maxDailyBookings: number | null;
  requireStaffOnShift: boolean;
};

export type RosterAvailabilityMember = {
  id: string;
  weekly_schedule: unknown;
};

export type RosterTimeOffRange = {
  member_id: string;
  /** Inclusive YYYY-MM-DD range, business-local. */
  starts_on: string;
  ends_on: string;
};

export type ComputePublicSlotsInput = {
  now: Date;
  timezone: string;
  durationMinutes: number;
  busy: BusyBlock[];
  /** Null = owner never set hours; falls back to Mon-Fri 09:00-17:00. */
  businessHours: BusinessHours | null;
  policy: PublicSlotPolicy;
  /** Active roster members; consulted only when requireStaffOnShift. */
  roster: RosterAvailabilityMember[];
  timeOff: RosterTimeOffRange[];
  /** Start instants of existing bookings (dedupe ledger) for the daily cap. */
  existingBookingStarts: Date[];
};

export type PublicSlot = { startIso: string; endIso: string };

const STEP_MS = 15 * 60_000;
const DAY_MS = 24 * 60 * 60 * 1000;

/**
 * Default availability when the owner never filled in business hours:
 * weekdays 9 to 5. An explicitly closed day (null) or a missing day on a
 * PARTIALLY specified schedule stays closed — ambiguity must never offer a
 * Sunday 3 PM the owner would have to honor.
 */
const DEFAULT_HOURS: BusinessHours = {
  mon: { open: "09:00", close: "17:00" },
  tue: { open: "09:00", close: "17:00" },
  wed: { open: "09:00", close: "17:00" },
  thu: { open: "09:00", close: "17:00" },
  fri: { open: "09:00", close: "17:00" }
};

/** Day window in minutes since local midnight, or null when closed. */
function dayWindow(
  hours: BusinessHours,
  weekday: keyof BusinessHours
): { openMin: number; closeMin: number } | null {
  const entry = hours[weekday];
  if (entry === undefined || entry === null) return null;
  const openMin = parseHmToMinutes(entry.open);
  const closeMin = parseHmToMinutes(entry.close);
  // parseBusinessHours already validated HH:MM, but stay fail-closed on a
  // hand-edited row where close does not follow open.
  if (openMin === null || closeMin === null || closeMin <= openMin) return null;
  return { openMin, closeMin };
}

export function computePublicSlots(input: ComputePublicSlotsInput): PublicSlot[] {
  const {
    now,
    timezone,
    durationMinutes,
    busy,
    policy,
    roster,
    timeOff,
    existingBookingStarts
  } = input;
  const durationMs = durationMinutes * 60_000;
  const bufferMs = policy.bufferMinutes * 60_000;
  const hours = input.businessHours ?? DEFAULT_HOURS;

  // Busy blocks expanded by the buffer on both sides: a slot must clear the
  // padding, not just the meeting itself.
  const padded = busy
    .map((b) => ({ start: b.start.getTime() - bufferMs, end: b.end.getTime() + bufferMs }))
    .sort((a, b) => a.start - b.start);

  // Latest bookable business-local calendar day (lexicographic ISO compare).
  const lastIsoDate = localClock(
    new Date(now.getTime() + policy.maxAdvanceDays * DAY_MS),
    timezone
  ).isoDate;

  // Daily cap: existing bookings grouped by business-local day.
  const bookedPerDay = new Map<string, number>();
  for (const start of existingBookingStarts) {
    const iso = localClock(start, timezone).isoDate;
    bookedPerDay.set(iso, (bookedPerDay.get(iso) ?? 0) + 1);
  }

  // Roster schedules parsed once; a member with no valid schedule counts as
  // always on shift (same semantics as route_to_team's availability filter).
  const schedules = roster.map((m) => ({
    id: m.id,
    windows: parseWeeklyWindows(m.weekly_schedule)
  }));
  const staffOnShift = (clock: ReturnType<typeof localClock>): boolean => {
    if (schedules.length === 0) return false;
    return schedules.some((m) => {
      const offToday = timeOff.some(
        (t) =>
          t.member_id === m.id && t.starts_on <= clock.isoDate && clock.isoDate <= t.ends_on
      );
      if (offToday) return false;
      return m.windows === null || isWithinWeeklyWindows(m.windows, clock);
    });
  };

  const earliest = now.getTime() + policy.minNoticeMinutes * 60_000;
  // First candidate: the next 15-minute boundary at or after the notice
  // horizon. Every UTC offset in use is a multiple of 15 minutes, so these
  // boundaries are business-local quarter boundaries too; the :00/:30
  // filter below runs in the business zone.
  let cursor = Math.ceil(earliest / STEP_MS) * STEP_MS;
  // Elapsed-time horizon, one day past the calendar limit; the isoDate
  // check below enforces the real business-local boundary.
  const horizon = now.getTime() + (policy.maxAdvanceDays + 1) * DAY_MS;

  const slots: PublicSlot[] = [];
  for (; cursor <= horizon; cursor += STEP_MS) {
    const start = new Date(cursor);
    const clock = localClock(start, timezone);
    if (clock.minutes % 30 !== 0) continue;
    if (clock.isoDate > lastIsoDate) break;

    const window = dayWindow(hours, clock.weekday);
    if (!window) continue;
    if (clock.minutes < window.openMin) continue;
    if (clock.minutes + durationMinutes > window.closeMin) continue;

    const cap = policy.maxDailyBookings;
    if (cap !== null && (bookedPerDay.get(clock.isoDate) ?? 0) >= cap) continue;

    if (policy.requireStaffOnShift && !staffOnShift(clock)) continue;

    const slotStart = cursor;
    const slotEnd = cursor + durationMs;
    const clear = padded.every((b) => slotEnd <= b.start || slotStart >= b.end);
    if (!clear) continue;

    slots.push({
      startIso: start.toISOString(),
      endIso: new Date(slotEnd).toISOString()
    });
  }
  return slots;
}
