/**
 * Agents — save a run's artifact into the Documents knowledge library.
 *
 *   POST /api/dashboard/agents/runs/:runId/save-document
 *        { businessId, title? }
 *
 * The artifact becomes a regular business document: the text is stored as
 * the original file in the business-docs bucket AND as the agent-facing
 * content_md (clipped to the documents cap) — no second Gemini ingest pass
 * is needed because the artifact is already clean text. Saved documents
 * default to the 'staff' audience so a generated artifact can never leak
 * to customer channels unless the owner deliberately widens it.
 */

import { randomUUID } from "node:crypto";
import { z } from "zod";
import { getAuthUser, requireBusinessRole } from "@/lib/auth";
import { isViewAsActive } from "@/lib/admin/view-as";
import { errorResponse, handleRouteError, successResponse } from "@/lib/api-response";
import { createSupabaseServiceClient } from "@/lib/supabase/server";
import { getBusiness } from "@/lib/db/businesses";
import { getAgentRun, getBusinessAgent } from "@/lib/agents/db";
import {
  countBusinessDocuments,
  deleteBusinessDocument,
  insertBusinessDocument
} from "@/lib/documents/db";
import {
  BUSINESS_DOCS_BUCKET,
  DOCUMENT_CONTENT_MD_MAX_CHARS,
  DOCUMENT_SUMMARY_MAX_CHARS,
  documentLimitForTier
} from "@/lib/documents/core";
import { logger } from "@/lib/logger";

export const dynamic = "force-dynamic";

const bodySchema = z.object({
  businessId: z.string().uuid(),
  title: z.string().min(1).max(200).optional()
});

type RouteContext = { params: Promise<{ runId: string }> };

export async function POST(request: Request, context: RouteContext) {
  try {
    const user = await getAuthUser();
    if (!user) return errorResponse("UNAUTHORIZED", "Authentication required");
    if (await isViewAsActive(user)) {
      return errorResponse("FORBIDDEN", "View-as is read-only; exit view-as to make changes", 403);
    }
    const { runId } = await context.params;
    if (!z.string().uuid().safeParse(runId).success) {
      return errorResponse("VALIDATION_ERROR", "Invalid run id");
    }
    const body = bodySchema.safeParse(await request.json().catch(() => null));
    if (!body.success) {
      return errorResponse("VALIDATION_ERROR", body.error.issues[0]?.message ?? "Invalid body");
    }
    // Saving into the knowledge library is a settings-level change, same
    // gate as uploading a document directly.
    if (!user.isAdmin) await requireBusinessRole(body.data.businessId, "manage_settings");

    const run = await getAgentRun(body.data.businessId, runId);
    if (!run) return errorResponse("NOT_FOUND", "Run not found", 404);
    if (run.status !== "succeeded" || !run.output_md) {
      return errorResponse("VALIDATION_ERROR", "This run has no output to save");
    }

    const business = await getBusiness(body.data.businessId);
    if (!business) return errorResponse("NOT_FOUND", "Business not found", 404);
    const limit = documentLimitForTier(business.tier);
    const existing = await countBusinessDocuments(body.data.businessId);
    if (existing >= limit) {
      return errorResponse(
        "VALIDATION_ERROR",
        `Document limit reached for your plan (${limit}). Delete a document or upgrade to add more.`
      );
    }

    const agent = await getBusinessAgent(body.data.businessId, run.agent_id);
    const agentName = agent?.name ?? "Agent";
    const title = (body.data.title?.trim() || run.output_filename.replace(/\.[a-z0-9]+$/i, "") || `${agentName} output`).slice(0, 200);

    const db = await createSupabaseServiceClient();
    const documentId = randomUUID();
    const safeName = (run.output_filename || "output.md")
      .replace(/[^A-Za-z0-9._-]/g, "_")
      .slice(0, 120);
    const storagePath = `${body.data.businessId}/${documentId}/${safeName}`;
    const bytes = Buffer.from(run.output_md, "utf8");
    const { error: uploadError } = await db.storage
      .from(BUSINESS_DOCS_BUCKET)
      .upload(storagePath, bytes, { contentType: run.output_mime_type || "text/markdown" });
    if (uploadError) {
      logger.warn("agents/save-document: storage upload failed", {
        businessId: body.data.businessId,
        runId,
        error: uploadError.message
      });
      return errorResponse("INTERNAL_SERVER_ERROR", "Saving the document failed");
    }

    const summary = `Generated by the "${agentName}" agent${
      run.input_filename ? ` from ${run.input_filename}` : ""
    }.`.slice(0, DOCUMENT_SUMMARY_MAX_CHARS);

    let document;
    try {
      document = await insertBusinessDocument({
        id: documentId,
        business_id: body.data.businessId,
        title,
        category: "generated",
        audience: "staff",
        storage_path: storagePath,
        mime_type: run.output_mime_type || "text/markdown",
        byte_size: bytes.byteLength,
        content_md: run.output_md.slice(0, DOCUMENT_CONTENT_MD_MAX_CHARS),
        summary,
        status: "ready"
      });
    } catch (err) {
      // Compensate the uploaded object so an insert failure leaves no orphan.
      const { error: removeError } = await db.storage
        .from(BUSINESS_DOCS_BUCKET)
        .remove([storagePath]);
      if (removeError) {
        logger.warn("agents/save-document: orphan cleanup failed", {
          businessId: body.data.businessId,
          storagePath,
          error: removeError.message
        });
      }
      throw err;
    }

    // Serial re-check closes the pre-insert cap race (same pattern as the
    // documents upload route).
    const afterInsert = await countBusinessDocuments(body.data.businessId);
    if (afterInsert > limit) {
      await deleteBusinessDocument(body.data.businessId, documentId);
      const { error: removeError } = await db.storage
        .from(BUSINESS_DOCS_BUCKET)
        .remove([storagePath]);
      if (removeError) {
        logger.warn("agents/save-document: over-cap cleanup failed", {
          businessId: body.data.businessId,
          storagePath,
          error: removeError.message
        });
      }
      return errorResponse(
        "VALIDATION_ERROR",
        `Document limit reached for your plan (${limit}). Delete a document or upgrade to add more.`
      );
    }

    return successResponse({ document });
  } catch (err) {
    return handleRouteError(err);
  }
}
