/**
 * Agents — save a run's artifact into the Documents knowledge library.
 *
 * Shared by the dashboard "Save as document" action and the run_agent
 * AiFlow step's saveDocument option, so both paths get identical cap
 * enforcement, storage/DB compensation, and audience semantics. The
 * artifact becomes a regular business document: the text is stored as the
 * original file in the business-docs bucket AND as the agent-facing
 * content_md (clipped to the documents cap) — no second Gemini ingest pass
 * is needed because the artifact is already clean text.
 */

import { randomUUID } from "node:crypto";
import { createSupabaseServiceClient } from "@/lib/supabase/server";
import { getBusiness } from "@/lib/db/businesses";
import {
  countBusinessDocuments,
  deleteBusinessDocument,
  insertBusinessDocument,
  type BusinessDocumentRow
} from "@/lib/documents/db";
import {
  BUSINESS_DOCS_BUCKET,
  DOCUMENT_CONTENT_MD_MAX_CHARS,
  DOCUMENT_SUMMARY_MAX_CHARS,
  documentLimitForTier
} from "@/lib/documents/core";
import { logger } from "@/lib/logger";
import type { AgentRunRow } from "./db";

type SupabaseClient = Awaited<ReturnType<typeof createSupabaseServiceClient>>;

export type SaveArtifactInput = {
  businessId: string;
  /** The succeeded run whose artifact is being saved. */
  run: Pick<
    AgentRunRow,
    "output_md" | "output_filename" | "output_mime_type" | "input_filename"
  >;
  /** Display name of the agent that produced the artifact. */
  agentName: string;
  /** Optional explicit title; falls back to the artifact filename. */
  title?: string;
  /**
   * Document audience. Flow-saved artifacts are pinned to 'staff' by the
   * caller — an automated run must never widen an artifact to customer
   * channels.
   */
  audience: "clients" | "staff" | "both";
};

export type SaveArtifactResult =
  | { ok: true; document: BusinessDocumentRow }
  | {
      ok: false;
      error: "no_output" | "business_not_found" | "document_limit" | "storage_failed";
      detail: string;
    };

/**
 * Persist a run artifact as a business document. Expected failures return
 * `{ ok: false }`; unexpected DB faults throw (callers decide whether that
 * is fatal — the dashboard 500s, the flow route reports a fileError).
 */
export async function saveAgentRunArtifact(
  input: SaveArtifactInput,
  client?: SupabaseClient
): Promise<SaveArtifactResult> {
  const { businessId, run, agentName } = input;
  if (!run.output_md) {
    return { ok: false, error: "no_output", detail: "This run has no output to save" };
  }

  const business = await getBusiness(businessId);
  if (!business) {
    return { ok: false, error: "business_not_found", detail: "Business not found" };
  }
  const limit = documentLimitForTier(business.tier);
  const existing = await countBusinessDocuments(businessId);
  if (existing >= limit) {
    return {
      ok: false,
      error: "document_limit",
      detail: `Document limit reached for your plan (${limit}). Delete a document or upgrade to add more.`
    };
  }

  const title = (
    input.title?.trim() ||
    run.output_filename.replace(/\.[a-z0-9]+$/i, "") ||
    `${agentName} output`
  ).slice(0, 200);

  const db = client ?? (await createSupabaseServiceClient());
  const documentId = randomUUID();
  const safeName = (run.output_filename || "output.md")
    .replace(/[^A-Za-z0-9._-]/g, "_")
    .slice(0, 120);
  const storagePath = `${businessId}/${documentId}/${safeName}`;
  const bytes = Buffer.from(run.output_md, "utf8");
  const { error: uploadError } = await db.storage
    .from(BUSINESS_DOCS_BUCKET)
    .upload(storagePath, bytes, { contentType: run.output_mime_type || "text/markdown" });
  if (uploadError) {
    logger.warn("agents/save-artifact: storage upload failed", {
      businessId,
      error: uploadError.message
    });
    return { ok: false, error: "storage_failed", detail: "Saving the document failed" };
  }

  const summary = `Generated by the "${agentName}" agent${
    run.input_filename ? ` from ${run.input_filename}` : ""
  }.`.slice(0, DOCUMENT_SUMMARY_MAX_CHARS);

  let document: BusinessDocumentRow;
  try {
    document = await insertBusinessDocument({
      id: documentId,
      business_id: businessId,
      title,
      category: "generated",
      audience: input.audience,
      storage_path: storagePath,
      mime_type: run.output_mime_type || "text/markdown",
      byte_size: bytes.byteLength,
      content_md: run.output_md.slice(0, DOCUMENT_CONTENT_MD_MAX_CHARS),
      summary,
      status: "ready"
    });
  } catch (err) {
    // Compensate the uploaded object so an insert failure leaves no orphan.
    const { error: removeError } = await db.storage
      .from(BUSINESS_DOCS_BUCKET)
      .remove([storagePath]);
    if (removeError) {
      logger.warn("agents/save-artifact: orphan cleanup failed", {
        businessId,
        storagePath,
        error: removeError.message
      });
    }
    throw err;
  }

  // Serial re-check closes the pre-insert cap race (same pattern as the
  // documents upload route).
  const afterInsert = await countBusinessDocuments(businessId);
  if (afterInsert > limit) {
    await deleteBusinessDocument(businessId, documentId);
    const { error: removeError } = await db.storage
      .from(BUSINESS_DOCS_BUCKET)
      .remove([storagePath]);
    if (removeError) {
      logger.warn("agents/save-artifact: over-cap cleanup failed", {
        businessId,
        storagePath,
        error: removeError.message
      });
    }
    return {
      ok: false,
      error: "document_limit",
      detail: `Document limit reached for your plan (${limit}). Delete a document or upgrade to add more.`
    };
  }

  return { ok: true, document };
}
