import type { Metadata } from "next";
import { LegalPage, LegalSection } from "@/components/legal/LegalPage";

const EFFECTIVE_DATE = "April 2, 2026";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How New Coworker collects, uses, shares, stores, and protects personal information.",
  alternates: {
    canonical: "/privacy"
  }
};

export default function PrivacyPolicyPage() {
  const contactEmail = process.env.CONTACT_EMAIL ?? "newcoworkerteam@gmail.com";

  return (
    <LegalPage
      eyebrow="Privacy Policy"
      title="Privacy Policy"
      summary="This Privacy Policy explains how New Coworker collects, uses, discloses, and safeguards information when businesses and their personnel use our website, onboarding flow, dashboard, messaging features, and AI-powered communication services."
      effectiveDate={EFFECTIVE_DATE}
    >
      <LegalSection title="1. Scope">
        <p>
          This Privacy Policy applies to information we collect through `newcoworker.com`, the New Coworker
          application, customer onboarding, account management, support interactions, and related services
          that help businesses deploy AI tools for calls, text messaging, email handling, workflow execution,
          and business memory.
        </p>
        <p>
          If you provide our services to your own customers, leads, tenants, patients, clients, or other end
          users, you are responsible for providing any notices and obtaining any consents required for your use
          of New Coworker.
        </p>
      </LegalSection>

      <LegalSection title="2. Information We Collect">
        <p>We may collect the following categories of information:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>Account and contact data, such as name, email address, phone number, business name, and login credentials.</li>
          <li>Business profile data, such as business type, service area, team size, workflow preferences, typical customer inquiries, and onboarding responses.</li>
          <li>Communications and content, such as messages submitted through the product, support emails, SMS interactions, and customer-configured memory or knowledge-base content.</li>
          <li>Billing and transaction data, such as subscription plan, billing period, payment status, and customer identifiers generated by our payment processor.</li>
          <li>Usage and diagnostic data, such as log events, feature activity, browser or device data, IP address, session timestamps, and performance telemetry.</li>
          <li>Provisioning and configuration data, such as infrastructure identifiers, voice-agent configuration, deployment status, and service-integrator metadata.</li>
        </ul>
      </LegalSection>

      <LegalSection title="3. How We Collect Information">
        <p>We collect information directly from you, automatically through your use of the service, and from service providers that support authentication, billing, hosting, communications, and infrastructure provisioning.</p>
        <p>For example, we receive information when you create an account, complete onboarding, purchase a subscription, send or receive SMS through a New Coworker workflow, contact support, or configure your AI coworker.</p>
      </LegalSection>

      <LegalSection title="4. How We Use Information">
        <p>We use information as reasonably necessary to:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>Provide, maintain, secure, and improve the platform and related services.</li>
          <li>Create and administer accounts, subscriptions, dashboards, and customer environments.</li>
          <li>Process payments, manage renewals, and send transactional notices.</li>
          <li>Provision infrastructure, phone and messaging capabilities, voice agents, and other service components.</li>
          <li>Train, configure, and operate customer-specific business memory, prompts, workflows, and assistant behavior within the service.</li>
          <li>Respond to support requests, enforce our terms, investigate misuse, and comply with law.</li>
          <li>Send administrative, operational, security, and service-related communications.</li>
        </ul>
      </LegalSection>

      <LegalSection title="5. Legal Bases">
        <p>
          Where applicable, we process personal information based on one or more of the following grounds:
          performance of a contract, legitimate interests in operating and securing the service, compliance with
          legal obligations, and consent where consent is required.
        </p>
      </LegalSection>

      <LegalSection title="6. AI, Communications, and Customer Content">
        <p>
          New Coworker is designed to help businesses automate and support communications, including calls,
          SMS, email, and workflow actions. Information submitted to the service may be processed by AI models
          and communications vendors in order to generate responses, route interactions, maintain business
          memory, and provide requested features.
        </p>
        <p>
          You should not use the service to submit regulated or highly sensitive information unless you and
          New Coworker have separately agreed in writing that the service is suitable for that use case and all
          required compliance obligations have been addressed.
        </p>
      </LegalSection>

      <LegalSection title="7. How We Share Information">
        <p>We may disclose information to the following categories of recipients:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>Service providers that help us operate the platform, including hosting, database, authentication, communications, payment, email, analytics, and AI vendors.</li>
          <li>Infrastructure and deployment partners that provision customer environments and related systems.</li>
          <li>Professional advisors, auditors, insurers, and legal counsel where reasonably necessary.</li>
          <li>Government authorities or other third parties when required by law, legal process, or to protect rights, safety, and security.</li>
          <li>Parties involved in an actual or proposed merger, financing, acquisition, reorganization, or sale of assets.</li>
        </ul>
        <p>
          Based on the current product architecture, these providers may include Supabase for authentication and
          database services, Stripe for billing, Twilio for messaging-related functionality, Resend for email
          delivery, Hostinger for infrastructure provisioning, and Inworld or other AI-related vendors used to
          power voice or model-based features.
        </p>
      </LegalSection>

      <LegalSection title="8. SMS and Calling Disclosures">
        <p>
          If you use SMS or calling features, you represent that you have the right to contact each recipient and
          that your campaigns, notifications, and conversational flows comply with applicable telecom, privacy,
          and marketing laws. Message frequency varies. Message and data rates may apply based on the recipient’s carrier plan.
        </p>
        <p>
          Recipients may reply `STOP` to opt out of SMS alerts and `START` to re-subscribe where supported.
          Reply `HELP` for assistance. Carriers are not liable for delayed or undelivered messages.
        </p>
      </LegalSection>

      <LegalSection title="9. Cookies and Similar Technologies">
        <p>
          We and our service providers may use cookies, local storage, session technologies, and similar tools
          to keep users signed in, remember onboarding progress, secure the application, understand usage, and
          improve performance. You can manage many browser-level controls through your device or browser settings.
        </p>
      </LegalSection>

      <LegalSection title="10. Data Retention">
        <p>
          We retain personal information for as long as reasonably necessary to provide the service, comply with
          legal obligations, resolve disputes, enforce agreements, maintain security, and support legitimate
          business needs. Retention periods vary by data type, sensitivity, operational need, and legal requirements.
        </p>
      </LegalSection>

      <LegalSection title="11. Security">
        <p>
          We use commercially reasonable administrative, technical, and organizational safeguards designed to
          protect information against unauthorized access, loss, misuse, or alteration. No system is completely
          secure, and we do not guarantee that information will always remain secure in every circumstance.
        </p>
      </LegalSection>

      <LegalSection title="12. International Processing">
        <p>
          Your information may be processed or stored in the United States and other jurisdictions where we or
          our service providers operate. Those jurisdictions may have data protection laws that differ from the
          laws where you reside.
        </p>
      </LegalSection>

      <LegalSection title="13. Your Rights and Choices">
        <p>
          Depending on where you live, you may have rights to request access to, correction of, deletion of, or
          portability of personal information, or to object to or limit certain processing. You may also be able
          to opt out of marketing communications while still receiving transactional or service messages.
        </p>
        <p>
          To submit a privacy request, email <a className="text-signal-teal hover:text-parchment" href={`mailto:${contactEmail}`}>{contactEmail}</a>.
          We may need to verify your identity before acting on a request.
        </p>
      </LegalSection>

      <LegalSection title="14. Children">
        <p>
          The service is intended for business use and not directed to children under 13. We do not knowingly
          collect personal information directly from children under 13 through the service.
        </p>
      </LegalSection>

      <LegalSection title="15. Changes to This Policy">
        <p>
          We may update this Privacy Policy from time to time. If we make material changes, we may post the
          revised version on the site, update the effective date above, and take additional steps if required by law.
        </p>
      </LegalSection>

      <LegalSection title="16. Contact Us">
        <p>
          Questions, requests, or concerns about this Privacy Policy may be sent to{" "}
          <a className="text-signal-teal hover:text-parchment" href={`mailto:${contactEmail}`}>{contactEmail}</a>.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
