-- Rolling per-thread conversation summary for /dashboard/chat.
--
-- HISTORY_TURNS=20 in src/app/api/dashboard/chat/route.ts caps how many
-- raw turns we replay back to Rowboat. For long-running threads
-- (post-PR #63 every thread is continuable, ChatGPT/Claude/Gemini-style)
-- everything older than the most recent 20 turns silently disappears
-- from the model's context. To preserve long-term recall we keep a
-- compact summary on the thread row, regenerated on the local model
-- whenever the thread accumulates another 20 messages worth of new
-- material. The next chat call prepends this summary as a system
-- message before the recent-turn tail so the agent sees:
--
--   <vault instructions>      ← static, set via syncVaultToVps
--   <conversation summary>    ← rolling, regenerated every 20 messages
--   <last 20 raw turns>       ← live tail
--   <new user message>
--
-- summary_message_count records how many messages the most recent
-- summary covered, so we can detect when it's stale (current count -
-- summary_message_count >= 20 → re-summarize) without re-reading the
-- summary text itself.

alter table dashboard_chat_threads
  add column if not exists summary_md text,
  add column if not exists summary_message_count integer not null default 0;

comment on column dashboard_chat_threads.summary_md is
  'Compact (~1500 char) rolling summary of all but the most recent 20 messages, regenerated by the summarizer when 20+ new messages have accrued since the last summary. Prepended as a system message in subsequent Rowboat calls.';

comment on column dashboard_chat_threads.summary_message_count is
  'Total message count at the time summary_md was last generated. The summarizer re-fires when total_messages - summary_message_count >= 20.';
