-- Per-VPS SSH keypair persistence
--
-- Each VPS provisioned through Hostinger gets its own ed25519 keypair so a
-- single compromised key never widens blast radius beyond one tenant. The
-- orchestrator generates the pair client-side, uploads the public half to
-- Hostinger, and stores both halves here (the private half is needed so the
-- orchestrator can SSH back in to run deploy-client.sh, and so admins can
-- debug-drop into tenant VPSes).
--
-- Security posture:
--   * RLS enabled; no policies = service_role-only access (Supabase bypasses
--     RLS for the service role). anon/authenticated have zero access.
--   * Private keys are stored in PEM as-is. Postgres storage is encrypted at
--     rest by Supabase (platform-managed). If we later want app-layer
--     encryption (pgsodium / libsodium), that's a follow-up — this table
--     already gates all access through a single app path
--     (`src/lib/db/vps-ssh-keys.ts`) so wrapping the private_key_pem column
--     is a surgical change, not a cross-cutting refactor.
--   * Private keys are NEVER exposed through PostgREST RPCs or views; the
--     only read path is the service-role-authenticated admin endpoint
--     `GET /api/admin/vps/:businessId/ssh-key`.

create table if not exists public.vps_ssh_keys (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  hostinger_vps_id text not null,
  -- Hostinger's numeric id for the uploaded public key, so we can detach /
  -- delete it on teardown without fuzzy-name matching.
  hostinger_public_key_id bigint,
  -- OpenSSH public key (single line, newline-terminated).
  public_key text not null,
  -- PKCS#8 PEM-encoded private key.
  private_key_pem text not null,
  -- SHA-256 fingerprint for audit / display (`SHA256:…`, matches `ssh-keygen -lf`).
  fingerprint_sha256 text not null,
  -- Username on the VPS where this key is authorized (root on fresh Hostinger VPS).
  ssh_username text not null default 'root',
  created_at timestamptz not null default now(),
  rotated_at timestamptz,
  -- One active keypair per VPS at any given time; rotations insert a new row
  -- and leave the old one present (with `rotated_at` set) for audit trails.
  constraint vps_ssh_keys_active_unique unique (hostinger_vps_id, rotated_at)
);

create index if not exists idx_vps_ssh_keys_business_id
  on public.vps_ssh_keys (business_id);

create index if not exists idx_vps_ssh_keys_hostinger_vps_id
  on public.vps_ssh_keys (hostinger_vps_id);

alter table public.vps_ssh_keys enable row level security;

-- No grants for anon / authenticated / PUBLIC. Only the service_role can
-- touch this table. If ops ever need to query it from hPanel, wrap it in a
-- SECURITY DEFINER function with explicit role checks — don't open the
-- table directly.
revoke all on table public.vps_ssh_keys from public;
revoke all on table public.vps_ssh_keys from anon;
revoke all on table public.vps_ssh_keys from authenticated;

-- Track the Hostinger billing subscription id per VPS so cancellation works
-- without a manual hPanel lookup. We extend the existing businesses table
-- rather than inventing a new one because the subscription is per-business.
alter table public.businesses
  add column if not exists hostinger_subscription_id text;

-- Track the Hostinger post-install script id we registered for the business,
-- so redeploys can update (PUT) the same script instead of racking up new
-- ones in the account.
alter table public.businesses
  add column if not exists hostinger_post_install_script_id bigint;

comment on table public.vps_ssh_keys is
  'Per-VPS SSH keypairs generated by the orchestrator. Service-role-only.';
comment on column public.vps_ssh_keys.private_key_pem is
  'PKCS#8 PEM. Secret — never returned via PostgREST RPC. Accessible only through src/lib/db/vps-ssh-keys.ts and the /api/admin/vps/:businessId/ssh-key endpoint.';
